// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface ActuatorHealthDto
 */
export interface ActuatorHealthDto {
    /**
     * Status of the application health
     * @type {string}
     * @memberof ActuatorHealthDto
     */
    status: ActuatorHealthDtoStatusEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum ActuatorHealthDtoStatusEnum {
    Unknown = 'UNKNOWN',
    Up = 'UP',
    Down = 'DOWN',
    OutOfService = 'OUT_OF_SERVICE',
}
