// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { AttributeCallbackMapping } from './';

/**
 * @export
 * @interface AttributeCallback
 */
export interface AttributeCallback {
    /**
     * Context part of callback URL
     * @type {string}
     * @memberof AttributeCallback
     */
    callbackContext?: string;
    /**
     * HTTP method of the callback. This value is required for connector callbacks and optional only for callbacks defined on resource objects.
     * @type {string}
     * @memberof AttributeCallback
     */
    callbackMethod?: string;
    /**
     * Mappings for the callback method
     * @type {Array<AttributeCallbackMapping>}
     * @memberof AttributeCallback
     */
    mappings: Array<AttributeCallbackMapping>;
    /**
     * Names of the attributes, within this same form, whose values this Attributes v2 callback consumes and is triggered by. Providing this field — even as an empty list — marks the callback as an Attributes v2 callback; an empty list means the callback fires once when the form opens (it depends on no other field). At most one of dependsOn or callbackContext may be set; a callback with neither field set defines no callback. Not allowed on RESOURCE attributes. These rules are enforced by the platform.
     * @type {Array<string>}
     * @memberof AttributeCallback
     */
    dependsOn?: Array<string>;
}
