// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { AttributeCallbackMapping } from './';

/**
 * @export
 * @interface AttributeCallback
 */
export interface AttributeCallback {
    /**
     * Context part of callback URL
     * @type {string}
     * @memberof AttributeCallback
     */
    callbackContext?: string;
    /**
     * HTTP method of the callback. This value is required for connector callbacks and optional only for callbacks defined on resource objects.
     * @type {string}
     * @memberof AttributeCallback
     */
    callbackMethod?: string;
    /**
     * Mappings for the callback method
     * @type {Array<AttributeCallbackMapping>}
     * @memberof AttributeCallback
     */
    mappings: Array<AttributeCallbackMapping>;
    /**
     * Names of the attributes this Attributes v2 callback consumes and is triggered by. Marks an NG (Attributes v2) callback; at most one of dependsOn / callbackContext may be set (neither = no callback). Forbidden on RESOURCE attributes. Enforced by Core.
     * @type {Array<string>}
     * @memberof AttributeCallback
     */
    dependsOn?: Array<string>;
}
