// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { RequestAttribute } from './';

/**
 * @export
 * @interface AuthorityInstanceRequestDto
 */
export interface AuthorityInstanceRequestDto {
    /**
     * Authority instance name
     * @type {string}
     * @memberof AuthorityInstanceRequestDto
     */
    name: string;
    /**
     * List of Authority instance Attributes
     * @type {Array<RequestAttribute>}
     * @memberof AuthorityInstanceRequestDto
     */
    attributes: Array<RequestAttribute>;
    /**
     * List of Custom Attributes
     * @type {Array<RequestAttribute>}
     * @memberof AuthorityInstanceRequestDto
     */
    customAttributes?: Array<RequestAttribute>;
    /**
     * UUID of Authority provider
     * @type {string}
     * @memberof AuthorityInstanceRequestDto
     */
    connectorUuid: string;
    /**
     * UUID of the Connector Interface (AUTHORITY) to bind this instance to. Required to select a specific version when the connector exposes more than one AUTHORITY interface (e.g. v2 and v3 side-by-side). When null, the authority targets a legacy v1 connector that declares no connector interface; if such a connector exposes exactly one AUTHORITY interface it is used.
     * @type {string}
     * @memberof AuthorityInstanceRequestDto
     */
    interfaceUuid?: string;
    /**
     * Authority instance Kind. Used only by v1 connectors (framework V1), which implement the legacy AttributesController and carry kind in the wire path. v2 connectors ignore it (they dispatch on connector interface).
     * @type {string}
     * @memberof AuthorityInstanceRequestDto
     */
    kind?: string;
}
