// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ConnectorInterfaceDto, NameAndUuidDto, ResponseAttribute } from './';

/**
 * @export
 * @interface AuthorityInstanceDto
 */
export interface AuthorityInstanceDto {
    /**
     * Object identifier
     * @type {string}
     * @memberof AuthorityInstanceDto
     */
    uuid: string;
    /**
     * Object Name
     * @type {string}
     * @memberof AuthorityInstanceDto
     */
    name: string;
    /**
     * List of Authority instance Attributes
     * @type {Array<ResponseAttribute>}
     * @memberof AuthorityInstanceDto
     */
    attributes: Array<ResponseAttribute>;
    /**
     * List of Custom Attributes
     * @type {Array<ResponseAttribute>}
     * @memberof AuthorityInstanceDto
     */
    customAttributes?: Array<ResponseAttribute>;
    /**
     * Status of Authority instance
     * @type {string}
     * @memberof AuthorityInstanceDto
     */
    status: string;
    /**
     * Connector (Authority provider) this instance belongs to
     * @type {NameAndUuidDto}
     * @memberof AuthorityInstanceDto
     */
    connector: NameAndUuidDto;
    /**
     * Connector Interface this Authority instance is bound to; null for legacy v1 connectors, which are identified by kind instead
     * @type {ConnectorInterfaceDto}
     * @memberof AuthorityInstanceDto
     */
    connectorInterface?: ConnectorInterfaceDto;
    /**
     * UUID of Authority provider; deprecated, use connector.uuid instead
     * @type {string}
     * @memberof AuthorityInstanceDto
     */
    connectorUuid?: string;
    /**
     * Name of Authority provider; deprecated, use connector.name instead
     * @type {string}
     * @memberof AuthorityInstanceDto
     */
    connectorName?: string;
    /**
     * Authority instance kind; present for legacy v1 connectors, null for v2/v3 authorities which are identified by connectorInterface
     * @type {string}
     * @memberof AuthorityInstanceDto
     */
    kind?: string;
}
