// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { OperationSupport } from './';

/**
 * Per-RA-profile capability advertisement. Operators query this before invoking register/cancel/etc. to know which actions an authority supports.
 * @export
 * @interface AvailableOperations
 */
export interface AvailableOperations {
    /**
     * List of operations the authority advertises for this RA profile.
     * @type {Array<OperationSupport>}
     * @memberof AvailableOperations
     */
    operations?: Array<OperationSupport>;
}
