// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    AttributeCallback,
    AttributeContentType,
    AttributeType,
    AttributeVersion,
    BaseAttributeConstraint,
    BaseAttributeContentDtoV3,
    BaseAttributeDtoV2,
    BaseAttributeDtoV3,
    CustomAttributeProperties,
    FieldMapping,
    ValueSource,
} from './';

/**
 * @type BaseAttributeDto
 * Base Attribute definition
 * @export
 */
export type BaseAttributeDto = BaseAttributeDtoV2 | BaseAttributeDtoV3;
