// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    AttributeCallback,
    AttributeContentType,
    AttributeType,
    AttributeVersion,
    BaseAttributeConstraint,
    BaseAttributeContentDtoV3,
    CustomAttributeProperties,
    CustomAttributeV3,
    DataAttributeV3,
    FieldMapping,
    GroupAttributeV3,
    InfoAttributeV3,
    MetadataAttributeV3,
    ValueSource,
} from './';

/**
 * @type BaseAttributeDtoV3
 * Base Attribute definition
 * @export
 */
export type BaseAttributeDtoV3 = CustomAttributeV3 | DataAttributeV3 | GroupAttributeV3 | InfoAttributeV3 | MetadataAttributeV3;
