// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { KeyUsage } from './';

/**
 * @export
 * @interface BulkTokenProfileKeyUsageRequestDto
 */
export interface BulkTokenProfileKeyUsageRequestDto {
    /**
     * Usages for the Key
     * @type {Array<KeyUsage>}
     * @memberof BulkTokenProfileKeyUsageRequestDto
     */
    usage: Array<KeyUsage>;
    /**
     * Token Profile UUIDs
     * @type {Array<string>}
     * @memberof BulkTokenProfileKeyUsageRequestDto
     */
    uuids: Array<string>;
}
