// tslint:disable
/**
 * Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.17.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface BulkActionMessageDto
 */
export interface BulkActionMessageDto {
    /**
     * Object identifier
     * @type {string}
     * @memberof BulkActionMessageDto
     */
    uuid: string;
    /**
     * Object Name
     * @type {string}
     * @memberof BulkActionMessageDto
     */
    name: string;
    /**
     * Message describing the associations of the objects that are preventing the bulk operation
     * @type {string}
     * @memberof BulkActionMessageDto
     */
    message: string;
}
