// tslint:disable
/**
 * Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.17.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface CancelPendingCertificateRequestDto
 */
export interface CancelPendingCertificateRequestDto {
    /**
     * Optional free-text reason from the user explaining why the pending operation is being cancelled. Recorded in the certificate event history.
     * @type {string}
     * @memberof CancelPendingCertificateRequestDto
     */
    reason?: string;
}
