// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { BaseAttributeDto } from './';

/**
 * Request to set the editable platform default request-attribute definitions.
 * @export
 * @interface CertificateRequestAttributesSettingsUpdateDto
 */
export interface CertificateRequestAttributesSettingsUpdateDto {
    /**
     * Ordered list of platform default request-attribute definitions
     * @type {Array<BaseAttributeDto>}
     * @memberof CertificateRequestAttributesSettingsUpdateDto
     */
    requestAttributes?: Array<BaseAttributeDto>;
    /**
     * Platform default for external-CSR strictness; an RA Profile inherits this when its own externalCsrValidationStrict is null
     * @type {boolean}
     * @memberof CertificateRequestAttributesSettingsUpdateDto
     */
    externalCsrValidationStrict?: boolean;
}
