// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    CertificateRegistrationSettingsUpdateDto,
    CertificateRequestAttributesSettingsUpdateDto,
    CertificateValidationSettingsUpdateDto,
} from './';

/**
 * @export
 * @interface CertificateSettingsUpdateDto
 */
export interface CertificateSettingsUpdateDto {
    /**
     * Settings of validation of certificates
     * @type {CertificateValidationSettingsUpdateDto}
     * @memberof CertificateSettingsUpdateDto
     */
    validation?: CertificateValidationSettingsUpdateDto;
    /**
     * Platform default request-attribute set
     * @type {CertificateRequestAttributesSettingsUpdateDto}
     * @memberof CertificateSettingsUpdateDto
     */
    requestAttributes?: CertificateRequestAttributesSettingsUpdateDto;
    /**
     * Certificate pre-registration settings
     * @type {CertificateRegistrationSettingsUpdateDto}
     * @memberof CertificateSettingsUpdateDto
     */
    registration?: CertificateRegistrationSettingsUpdateDto;
}
