// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface CertificateRegistrationSettingsUpdateDto
 */
export interface CertificateRegistrationSettingsUpdateDto {
    /**
     * Default issuance window in days, applied when a pre-registration omits an explicit expiry
     * @type {number}
     * @memberof CertificateRegistrationSettingsUpdateDto
     */
    defaultIssuanceWindowDays?: number;
    /**
     * Maximum failed challenge-verification attempts before the registration authorization locks
     * @type {number}
     * @memberof CertificateRegistrationSettingsUpdateDto
     */
    maxFailedAttempts?: number;
}
