// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CertificateRegistrationState } from './';

/**
 * @export
 * @interface CertificateRegistrationDetailDto
 */
export interface CertificateRegistrationDetailDto {
    /**
     * Registration authorization state
     * @type {CertificateRegistrationState}
     * @memberof CertificateRegistrationDetailDto
     */
    state?: CertificateRegistrationState;
    /**
     * Issuance deadline for completing the pre-registered certificate
     * @type {string}
     * @memberof CertificateRegistrationDetailDto
     */
    expiresAt?: string;
    /**
     * Number of failed challenge-verification attempts recorded
     * @type {number}
     * @memberof CertificateRegistrationDetailDto
     */
    failedAttempts?: number;
}
