// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface CertificateExtension
 */
export interface CertificateExtension {
    /**
     * OID of the X.509 extension (dotted-decimal, RFC 5280)
     * @type {string}
     * @memberof CertificateExtension
     */
    oid: string;
    /**
     * Whether the extension is marked critical
     * @type {boolean}
     * @memberof CertificateExtension
     */
    critical: boolean;
    /**
     * DER-encoded extension value, Base64-encoded
     * @type {string}
     * @memberof CertificateExtension
     */
    valueBase64: string;
}
