// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CipherRequestData, RequestAttribute } from './';

/**
 * @export
 * @interface CipherDataRequestDto
 */
export interface CipherDataRequestDto {
    /**
     * List of cipher Attributes
     * @type {Array<RequestAttribute>}
     * @memberof CipherDataRequestDto
     */
    cipherAttributes: Array<RequestAttribute>;
    /**
     * Encrypted/decrypted data
     * @type {Array<CipherRequestData>}
     * @memberof CipherDataRequestDto
     */
    cipherData: Array<CipherRequestData>;
}
