// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CertificateExtension, RequestAttribute } from './';

/**
 * Pre-registration request for a v3 authority. Reserves a slot/identity at the CA before any CSR exists; the returned tracking handle is later used to complete issuance.
 * @export
 * @interface ClientCertificateRegistrationRequest
 */
export interface ClientCertificateRegistrationRequest {
    /**
     * Subject DN. Optional per RFC 5280 §4.1.2.6: an empty subject is permitted when subject naming information is carried entirely in the Subject Alternative Name extension (in which case the subjectAltName extension MUST be marked critical at issuance). At least one of subjectDn or subjectAltName must be non-empty — enforced by the cross-field {@code subjectIdentificationProvided} constraint.
     * @type {string}
     * @memberof ClientCertificateRegistrationRequest
     */
    subjectDn?: string;
    /**
     * Subject Alternative Name in RFC 5280 textual form (e.g. DNS:foo,IP:1.2.3.4,email:x@y). SAN MUST be carried here ONLY — do not also include it as OID 2.5.29.17 in extensions[]. Connectors reject duplicate-source requests with VALIDATION_FAILED. Required when subjectDn is empty (see RFC 5280 §4.1.2.6).
     * @type {string}
     * @memberof ClientCertificateRegistrationRequest
     */
    subjectAltName?: string;
    /**
     * Structured certificate extensions (OID + critical + base64 value). All extensions OTHER than SAN go here.
     * @type {Array<CertificateExtension>}
     * @memberof ClientCertificateRegistrationRequest
     */
    extensions?: Array<CertificateExtension>;
    /**
     * Authority-defined registration attributes (e.g., subject DN template, validity hints).
     * @type {Array<RequestAttribute>}
     * @memberof ClientCertificateRegistrationRequest
     */
    attributes?: Array<RequestAttribute>;
    /**
     * RA-profile-scoped override attributes for the registration.
     * @type {Array<RequestAttribute>}
     * @memberof ClientCertificateRegistrationRequest
     */
    raProfileAttributes?: Array<RequestAttribute>;
    /**
     * List of Custom Attributes
     * @type {Array<RequestAttribute>}
     * @memberof ClientCertificateRegistrationRequest
     */
    customAttributes?: Array<RequestAttribute>;
}
