// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CertificateExtension, RequestAttribute } from './';

/**
 * Pre-registration request for a v3 authority. Reserves a slot/identity at the CA before any CSR exists; the returned tracking handle is later used to complete issuance.
 * @export
 * @interface ClientCertificateRegistrationRequest
 */
export interface ClientCertificateRegistrationRequest {
    /**
     * Subject DN. Optional per RFC 5280 §4.1.2.6: an empty subject is permitted when subject naming information is carried entirely in the Subject Alternative Name extension (in which case the subjectAltName extension MUST be marked critical at issuance). At least one of subjectDn, subjectAltName, or csrAttributes must provide subject identity — enforced by the cross-field {@code subjectIdentificationProvided} constraint.
     * @type {string}
     * @memberof ClientCertificateRegistrationRequest
     */
    subjectDn?: string;
    /**
     * Subject Alternative Name in RFC 5280 textual form (e.g. DNS:foo,IP:1.2.3.4,email:x@y). SAN MUST be carried here ONLY — do not also include it as OID 2.5.29.17 in extensions[]. Connectors reject duplicate-source requests with VALIDATION_FAILED. Provides subject identity when subjectDn is empty (see RFC 5280 §4.1.2.6); csrAttributes is a further alternative.
     * @type {string}
     * @memberof ClientCertificateRegistrationRequest
     */
    subjectAltName?: string;
    /**
     * Structured certificate extensions (OID + critical + base64 value). All extensions OTHER than SAN go here.
     * @type {Array<CertificateExtension>}
     * @memberof ClientCertificateRegistrationRequest
     */
    extensions?: Array<CertificateExtension>;
    /**
     * Structured request-attribute identity content (subject RDNs, SANs, extensions) — the typed alternative to the flat subjectDn/subjectAltName/extensions above, mirroring the issue path. When provided, the platform projects it into the registration identity; the flat subjectDn/subjectAltName/extensions are the simple alternative. Provide the identity via csrAttributes OR the flat fields, not both.
     * @type {Array<RequestAttribute>}
     * @memberof ClientCertificateRegistrationRequest
     */
    csrAttributes?: Array<RequestAttribute>;
    /**
     * Authority-defined registration attributes (e.g., subject DN template, validity hints).
     * @type {Array<RequestAttribute>}
     * @memberof ClientCertificateRegistrationRequest
     */
    attributes?: Array<RequestAttribute>;
    /**
     * RA-profile-scoped override attributes for the registration.
     * @type {Array<RequestAttribute>}
     * @memberof ClientCertificateRegistrationRequest
     */
    raProfileAttributes?: Array<RequestAttribute>;
    /**
     * List of Custom Attributes
     * @type {Array<RequestAttribute>}
     * @memberof ClientCertificateRegistrationRequest
     */
    customAttributes?: Array<RequestAttribute>;
    /**
     * Optional UUID of the user to set as the certificate owner at registration. When omitted, the registering user becomes the owner. The value set here is preserved when the pre-registered certificate is later issued.
     * @type {string}
     * @memberof ClientCertificateRegistrationRequest
     */
    ownerUuid?: string;
    /**
     * Optional set of group UUIDs to associate with the certificate at registration. When provided, it replaces any existing group set. The groups set here are preserved when the pre-registered certificate is later issued.
     * @type {Array<string>}
     * @memberof ClientCertificateRegistrationRequest
     */
    groupUuids?: Array<string>;
    /**
     * Authorization secret (challenge) that gates completion of this pre-registered certificate. Write-only and optional — the operator supplies it to opt the registration into challenge-gated issuance; the platform never generates one. Issuing a pre-registered certificate is currently the only challenge-verified completion path; renewal and rekey requests for a certificate with an active registration are rejected (fail-closed) until challenge-gated successor handling is added.
     * @type {string}
     * @memberof ClientCertificateRegistrationRequest
     */
    authorizationSecret?: string;
    /**
     * Optional absolute deadline by which the completion request must be presented — a valid challenge must be supplied before this instant. It gates the completion request, not the final issuance: when the request is approved or otherwise processed asynchronously, issuance may finalize shortly after the deadline. When omitted, the platform applies the default registration issuance window.
     * @type {string}
     * @memberof ClientCertificateRegistrationRequest
     */
    expiresAt?: string;
}
