// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CertificateRequestFormat, RequestAttribute } from './';

/**
 * @export
 * @interface ClientCertificateIssueRequestDto
 */
export interface ClientCertificateIssueRequestDto {
    /**
     * List of attributes to create CSR. Required if CSR is not provided
     * @type {Array<RequestAttribute>}
     * @memberof ClientCertificateIssueRequestDto
     */
    csrAttributes?: Array<RequestAttribute>;
    /**
     * List of attributes to sign the CSR
     * @type {Array<RequestAttribute>}
     * @memberof ClientCertificateIssueRequestDto
     */
    signatureAttributes?: Array<RequestAttribute>;
    /**
     * List of attributes to sign the alternative private key
     * @type {Array<RequestAttribute>}
     * @memberof ClientCertificateIssueRequestDto
     */
    altSignatureAttributes?: Array<RequestAttribute>;
    /**
     * Certificate signing request encoded as Base64 string
     * @type {string}
     * @memberof ClientCertificateIssueRequestDto
     */
    request: string;
    /**
     * Certificate signing request format
     * @type {CertificateRequestFormat}
     * @memberof ClientCertificateIssueRequestDto
     */
    format?: CertificateRequestFormat;
    /**
     * Token Profile UUID. Required if CSR is not uploaded
     * @type {string}
     * @memberof ClientCertificateIssueRequestDto
     */
    tokenProfileUuid?: string;
    /**
     * Key UUID. Required if CSR is not uploaded
     * @type {string}
     * @memberof ClientCertificateIssueRequestDto
     */
    keyUuid?: string;
    /**
     * Token Profile UUID for the alternative key.
     * @type {string}
     * @memberof ClientCertificateIssueRequestDto
     */
    altTokenProfileUuid?: string;
    /**
     * Alternative Key UUID.
     * @type {string}
     * @memberof ClientCertificateIssueRequestDto
     */
    altKeyUuid?: string;
    /**
     * List of RA Profile related Attributes to issue Certificate
     * @type {Array<RequestAttribute>}
     * @memberof ClientCertificateIssueRequestDto
     */
    attributes: Array<RequestAttribute>;
    /**
     * List of Custom Attributes
     * @type {Array<RequestAttribute>}
     * @memberof ClientCertificateIssueRequestDto
     */
    customAttributes?: Array<RequestAttribute>;
    /**
     * One-time authorization secret proving the caller may complete a pre-registered certificate. Write-only; ignored for certificates without an active registration.
     * @type {string}
     * @memberof ClientCertificateIssueRequestDto
     */
    authorizationSecret?: string;
}
