// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ProtectionMethod, ProtocolCertificateAssociationsRequestDto, RequestAttribute } from './';

/**
 * @export
 * @interface CmpProfileRequestDto
 */
export interface CmpProfileRequestDto {
    /**
     * Description of the CMP Profile
     * @type {string}
     * @memberof CmpProfileRequestDto
     */
    description?: string;
    /**
     * RA Profile UUID that the CMP Profile is associated with
     * @type {string}
     * @memberof CmpProfileRequestDto
     */
    raProfileUuid?: string;
    /**
     * List of Attributes to issue Certificate for the associated RA Profile. Required when RA Profile UUID is provided
     * @type {Array<RequestAttribute>}
     * @memberof CmpProfileRequestDto
     */
    issueCertificateAttributes?: Array<RequestAttribute>;
    /**
     * List of Attributes to revoke Certificate for the associated RA Profile. Required when RA Profile UUID is provided
     * @type {Array<RequestAttribute>}
     * @memberof CmpProfileRequestDto
     */
    revokeCertificateAttributes?: Array<RequestAttribute>;
    /**
     * List of Custom Attributes for CMP Profile
     * @type {Array<RequestAttribute>}
     * @memberof CmpProfileRequestDto
     */
    customAttributes?: Array<RequestAttribute>;
    /**
     * Protection Method for the CMP Request
     * @type {ProtectionMethod}
     * @memberof CmpProfileRequestDto
     */
    requestProtectionMethod: ProtectionMethod;
    /**
     * Protection Method for the CMP Response
     * @type {ProtectionMethod}
     * @memberof CmpProfileRequestDto
     */
    responseProtectionMethod: ProtectionMethod;
    /**
     * Shared secret for the CMP Request, used when Protection Method is Shared Secret. Required when creating a CMP Profile. When editing, a blank or omitted value keeps the existing shared secret; a value is required if no shared secret is stored yet.
     * @type {string}
     * @memberof CmpProfileRequestDto
     */
    sharedSecret?: string;
    /**
     * UUID of the Certificate to be used as signing certificate for CMP responses. Required when Protection Method is Signature
     * @type {string}
     * @memberof CmpProfileRequestDto
     */
    signingCertificateUuid?: string;
    /**
     * Associations to set for certificates issued by the protocol
     * @type {ProtocolCertificateAssociationsRequestDto}
     * @memberof CmpProfileRequestDto
     */
    certificateAssociations?: ProtocolCertificateAssociationsRequestDto;
    /**
     * Name of the CMP Profile
     * @type {string}
     * @memberof CmpProfileRequestDto
     */
    name: string;
    /**
     * Variant of the CMP Profile
     * @type {string}
     * @memberof CmpProfileRequestDto
     */
    variant: CmpProfileRequestDtoVariantEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum CmpProfileRequestDtoVariantEnum {
    V2 = 'v2',
    V23gpp = 'v2_3gpp',
    V3 = 'v3',
}
