// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ConnectorStatus } from './';

/**
 * @export
 * @interface ConnectorSummaryDto
 */
export interface ConnectorSummaryDto {
    /**
     * Object identifier
     * @type {string}
     * @memberof ConnectorSummaryDto
     */
    uuid: string;
    /**
     * Object Name
     * @type {string}
     * @memberof ConnectorSummaryDto
     */
    name: string;
    /**
     * URL of the Connector
     * @type {string}
     * @memberof ConnectorSummaryDto
     */
    url: string;
    /**
     * Status of the Connector
     * @type {ConnectorStatus}
     * @memberof ConnectorSummaryDto
     */
    status: ConnectorStatus;
}
