// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { AuthType, RequestAttribute } from './';

/**
 * @export
 * @interface ConnectorRequestDto
 */
export interface ConnectorRequestDto {
    /**
     * Name of the Connector
     * @type {string}
     * @memberof ConnectorRequestDto
     */
    name: string;
    /**
     * URL of the Connector to connect
     * @type {string}
     * @memberof ConnectorRequestDto
     */
    url: string;
    /**
     * Type of authentication for the Connector
     * @type {AuthType}
     * @memberof ConnectorRequestDto
     */
    authType: AuthType;
    /**
     * List of authentication Attributes. Required if the authentication type is not NONE
     * @type {Array<RequestAttribute>}
     * @memberof ConnectorRequestDto
     */
    authAttributes?: Array<RequestAttribute>;
    /**
     * List of Custom Attributes
     * @type {Array<RequestAttribute>}
     * @memberof ConnectorRequestDto
     */
    customAttributes?: Array<RequestAttribute>;
    /**
     * UUID of the Proxy
     * @type {string}
     * @memberof ConnectorRequestDto
     */
    proxyUuid?: string;
    /**
     * Code of the Proxy that forwarded this registration request
     * @type {string}
     * @memberof ConnectorRequestDto
     */
    proxyCode?: string;
}
