// tslint:disable
/**
 * Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.17.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { AuthType, ConnectorStatus, FunctionGroupDto, ProxyDto, ResponseAttribute } from './';

/**
 * @export
 * @interface ConnectorDto
 */
export interface ConnectorDto {
    /**
     * Object identifier
     * @type {string}
     * @memberof ConnectorDto
     */
    uuid: string;
    /**
     * Object Name
     * @type {string}
     * @memberof ConnectorDto
     */
    name: string;
    /**
     * URL of the Connector
     * @type {string}
     * @memberof ConnectorDto
     */
    url: string;
    /**
     * Type of authentication for the Connector
     * @type {AuthType}
     * @memberof ConnectorDto
     */
    authType: AuthType;
    /**
     * List of Attributes for the authentication type
     * @type {Array<ResponseAttribute>}
     * @memberof ConnectorDto
     */
    authAttributes?: Array<ResponseAttribute>;
    /**
     * Status of the Connector
     * @type {ConnectorStatus}
     * @memberof ConnectorDto
     */
    status: ConnectorStatus;
    /**
     * Proxy for message queue routing. When set, connector communicates via message queue proxy. When null, connector uses direct REST communication.
     * @type {ProxyDto}
     * @memberof ConnectorDto
     */
    proxy?: ProxyDto;
    /**
     * List of Function Groups implemented by the Connector
     * @type {Array<FunctionGroupDto>}
     * @memberof ConnectorDto
     */
    functionGroups: Array<FunctionGroupDto>;
    /**
     * List of Custom Attributes
     * @type {Array<ResponseAttribute>}
     * @memberof ConnectorDto
     */
    customAttributes?: Array<ResponseAttribute>;
}
