// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { AuthType, ProxyDto, RequestAttribute } from './';

/**
 * @export
 * @interface ConnectRequestDto
 */
export interface ConnectRequestDto {
    /**
     * URL of the Connector to connect
     * @type {string}
     * @memberof ConnectRequestDto
     */
    url: string;
    /**
     * UUID of the Connector. Mandatory if connection is needed for the same Connector
     * @type {string}
     * @memberof ConnectRequestDto
     */
    uuid?: string;
    /**
     * Type of authentication for the Connector
     * @type {AuthType}
     * @memberof ConnectRequestDto
     */
    authType: AuthType;
    /**
     * List of authentication Attributes. Required if the authentication type is not NONE
     * @type {Array<RequestAttribute>}
     * @memberof ConnectRequestDto
     */
    authAttributes?: Array<RequestAttribute>;
    /**
     * Proxy for message queue routing. When set, connector communicates via message queue proxy. When null, connector uses direct REST communication.
     * @type {ProxyDto}
     * @memberof ConnectRequestDto
     */
    proxy?: ProxyDto;
}
