// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface ConnectorMetadataPromotionRequestDto
 */
export interface ConnectorMetadataPromotionRequestDto {
    /**
     * Metadata UUID
     * @type {string}
     * @memberof ConnectorMetadataPromotionRequestDto
     */
    uuid: string;
    /**
     * Connector UUID
     * @type {string}
     * @memberof ConnectorMetadataPromotionRequestDto
     */
    connectorUuid: string;
}
