// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CertificateExtensionOidPropertiesDto, ExtensionValueEncoding, RdnAttributeTypeOidPropertiesDto } from './';

/**
 * @type CustomOidEntryDetailResponseDtoAdditionalProperties
 * Additional properties depending on the OID category
 * @export
 */
export type CustomOidEntryDetailResponseDtoAdditionalProperties = CertificateExtensionOidPropertiesDto | RdnAttributeTypeOidPropertiesDto;
