// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface DateTimeAttributeConstraintData
 */
export interface DateTimeAttributeConstraintData {
    /**
     * Start of the datetime for validation
     * @type {string}
     * @memberof DateTimeAttributeConstraintData
     */
    from?: string;
    /**
     * End of the datetime for validation
     * @type {string}
     * @memberof DateTimeAttributeConstraintData
     */
    to?: string;
}
