// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface EnumItemDto
 */
export interface EnumItemDto {
    /**
     * Enum item code
     * @type {string}
     * @memberof EnumItemDto
     */
    code: string;
    /**
     * Enum item display label
     * @type {string}
     * @memberof EnumItemDto
     */
    label: string;
    /**
     * Enum item description
     * @type {string}
     * @memberof EnumItemDto
     */
    description?: string;
}
