// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { PaginationRequestDto } from './';

/**
 * @export
 * @interface EventHistoryRequestDto
 */
export interface EventHistoryRequestDto {
    /**
     * Pagination parameters for the list of event history entries.
     * @type {PaginationRequestDto}
     * @memberof EventHistoryRequestDto
     */
    pagination?: PaginationRequestDto;
    /**
     * Pagination parameters for the list of individual object histories within each event history entry.
     * @type {PaginationRequestDto}
     * @memberof EventHistoryRequestDto
     */
    objectsPagination?: PaginationRequestDto;
}
