// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { FilterFieldSource } from './';

/**
 * @export
 * @interface ExecutionItemRequestDto
 */
export interface ExecutionItemRequestDto {
    /**
     * Source of the field in the execution item
     * @type {FilterFieldSource}
     * @memberof ExecutionItemRequestDto
     */
    fieldSource?: FilterFieldSource;
    /**
     * Field identifier of the execution item
     * @type {string}
     * @memberof ExecutionItemRequestDto
     */
    fieldIdentifier?: string;
    /**
     * UUID of the Notification profile
     * @type {string}
     * @memberof ExecutionItemRequestDto
     */
    notificationProfileUuid?: string;
    /**
     * @type {any}
     * @memberof ExecutionItemRequestDto
     */
    data?: any | null;
    /**
     * Source field source for mapping (META, DATA, or CUSTOM). When set, value is read from this source instead of static data. Must be provided together with sourceFieldIdentifier; neither field is valid on its own.
     * @type {FilterFieldSource}
     * @memberof ExecutionItemRequestDto
     */
    sourceFieldSource?: FilterFieldSource;
    /**
     * Source field identifier for mapping (format: name|ContentType). Must be provided together with sourceFieldSource; neither field is valid on its own.
     * @type {string}
     * @memberof ExecutionItemRequestDto
     */
    sourceFieldIdentifier?: string;
}
