// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { FieldSource, FieldType, MappedField } from './';

/**
 * @type ExtensionMappedField
 * Maps an attribute value to an X.509 extension
 * @export
 */
export type ExtensionMappedField = MappedField;
