// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    ExtensionMappedField,
    ExtensionValueEncoding,
    FieldSource,
    FieldType,
    GeneralNameType,
    RdnMappedField,
    SanMappedField,
} from './';

/**
 * @type FieldMappingFieldsInner
 * @export
 */
export type FieldMappingFieldsInner = ExtensionMappedField | RdnMappedField | SanMappedField;
