// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { FieldMappingFieldsInner, ObjectType } from './';

/**
 * Declares which certificate (or other object) fields an attribute value projects into
 * @export
 * @interface FieldMapping
 */
export interface FieldMapping {
    /**
     * Object type this mapping applies to
     * @type {ObjectType}
     * @memberof FieldMapping
     */
    objectType: ObjectType;
    /**
     * One or more target fields (supports 1-to-many, e.g. CN + dNSName from a single attribute)
     * @type {Array<FieldMappingFieldsInner>}
     * @memberof FieldMapping
     */
    fields: Array<FieldMappingFieldsInner>;
}
