// tslint:disable
/**
 * Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.17.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Fingerprint DTO for certificate operations
 * @export
 * @interface FingerprintDto
 */
export interface FingerprintDto {
    /**
     * Fingerprint of the certificate
     * @type {string}
     * @memberof FingerprintDto
     */
    fingerprint: string;
}
