// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    ManagedSigningType,
    OneTimeKeyManagedSigningRequestDto,
    RequestAttribute,
    SigningScheme,
    StaticKeyManagedSigningRequestDto,
} from './';

/**
 * @type ManagedSigningRequestSchemeInterface
 * Managed signing request configuration dependent on the managed signing type
 * @export
 */
export type ManagedSigningRequestSchemeInterface = OneTimeKeyManagedSigningRequestDto | StaticKeyManagedSigningRequestDto;
