// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { FieldSource, FieldType } from './';

/**
 * Describes a single target field within an object; concrete type is determined by fieldType
 * @export
 * @interface MappedField
 */
export interface MappedField {
    /**
     * Field type, determines the concrete subtype
     * @type {FieldType}
     * @memberof MappedField
     */
    fieldType: FieldType;
    /**
     * Ordering index for fields of the same type (e.g. RDN components); ascending
     * @type {number}
     * @memberof MappedField
     */
    order?: number;
    /**
     * Provenance of the value when reconciling CSR vs platform-projected values
     * @type {FieldSource}
     * @memberof MappedField
     */
    source?: FieldSource;
}
