// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface NameAndUuidDto
 */
export interface NameAndUuidDto {
    /**
     * Object identifier
     * @type {string}
     * @memberof NameAndUuidDto
     */
    uuid: string;
    /**
     * Object Name
     * @type {string}
     * @memberof NameAndUuidDto
     */
    name: string;
}
