// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface NameAndIdDto
 */
export interface NameAndIdDto {
    /**
     * Object identifier
     * @type {number}
     * @memberof NameAndIdDto
     */
    id: number;
    /**
     * Object name
     * @type {string}
     * @memberof NameAndIdDto
     */
    name: string;
}
