// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CertificateOperationKind } from './';

/**
 * Per-operation support flags for an authority/RA profile.
 * @export
 * @interface OperationSupport
 */
export interface OperationSupport {
    /**
     * Operation kind (ISSUE, RENEW, REVOKE, REGISTER).
     * @type {CertificateOperationKind}
     * @memberof OperationSupport
     */
    operation: CertificateOperationKind;
    /**
     * Whether the operation is supported by this authority.
     * @type {boolean}
     * @memberof OperationSupport
     */
    supported?: boolean;
    /**
     * Whether the operation may complete asynchronously (HTTP 202 + status polling).
     * @type {boolean}
     * @memberof OperationSupport
     */
    asyncSupported?: boolean;
    /**
     * Whether an in-flight asynchronous execution of this operation can be cancelled.
     * @type {boolean}
     * @memberof OperationSupport
     */
    cancelSupported?: boolean;
}
