// tslint:disable
/**
 * Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.17.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { EventHistoryDto } from './';

/**
 * @export
 * @interface PaginationResponseDtoEventHistoryDto
 */
export interface PaginationResponseDtoEventHistoryDto {
    /**
     * Items returned
     * @type {Array<EventHistoryDto>}
     * @memberof PaginationResponseDtoEventHistoryDto
     */
    items: Array<EventHistoryDto>;
    /**
     * Number of entries per page
     * @type {number}
     * @memberof PaginationResponseDtoEventHistoryDto
     */
    itemsPerPage: number;
    /**
     * Page number for the request
     * @type {number}
     * @memberof PaginationResponseDtoEventHistoryDto
     */
    pageNumber: number;
    /**
     * Number of pages available
     * @type {number}
     * @memberof PaginationResponseDtoEventHistoryDto
     */
    totalPages: number;
    /**
     * Number of items available
     * @type {number}
     * @memberof PaginationResponseDtoEventHistoryDto
     */
    totalItems: number;
}
