// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ObjectEventHistoryDto } from './';

/**
 * @export
 * @interface PaginationResponseDtoObjectEventHistoryDto
 */
export interface PaginationResponseDtoObjectEventHistoryDto {
    /**
     * Items returned
     * @type {Array<ObjectEventHistoryDto>}
     * @memberof PaginationResponseDtoObjectEventHistoryDto
     */
    items: Array<ObjectEventHistoryDto>;
    /**
     * Number of entries per page
     * @type {number}
     * @memberof PaginationResponseDtoObjectEventHistoryDto
     */
    itemsPerPage: number;
    /**
     * Page number for the request
     * @type {number}
     * @memberof PaginationResponseDtoObjectEventHistoryDto
     */
    pageNumber: number;
    /**
     * Number of pages available
     * @type {number}
     * @memberof PaginationResponseDtoObjectEventHistoryDto
     */
    totalPages: number;
    /**
     * Number of items available
     * @type {number}
     * @memberof PaginationResponseDtoObjectEventHistoryDto
     */
    totalItems: number;
}
