// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CertificateSettingsDto, UtilsSettingsDto } from './';

/**
 * @export
 * @interface PlatformSettingsDto
 */
export interface PlatformSettingsDto {
    /**
     * Utils settings of the platform
     * @type {UtilsSettingsDto}
     * @memberof PlatformSettingsDto
     */
    utils?: UtilsSettingsDto;
    /**
     * Settings applicable to all certificates in inventory by default
     * @type {CertificateSettingsDto}
     * @memberof PlatformSettingsDto
     */
    certificates?: CertificateSettingsDto;
}
