// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ConnectorSummaryDto, ProxyStatus } from './';

/**
 * @export
 * @interface ProxyDto
 */
export interface ProxyDto {
    /**
     * Object identifier
     * @type {string}
     * @memberof ProxyDto
     */
    uuid: string;
    /**
     * Object Name
     * @type {string}
     * @memberof ProxyDto
     */
    name: string;
    /**
     * Detailed description of the Proxy
     * @type {string}
     * @memberof ProxyDto
     */
    description?: string;
    /**
     * Code of the Proxy
     * @type {string}
     * @memberof ProxyDto
     */
    code: string;
    /**
     * Status of the Proxy
     * @type {ProxyStatus}
     * @memberof ProxyDto
     */
    status: ProxyStatus;
    /**
     * Timestamp of the last activity from the Proxy
     * @type {string}
     * @memberof ProxyDto
     */
    lastActivity?: string;
    /**
     * List of Connectors associated with the Proxy
     * @type {Array<ConnectorSummaryDto>}
     * @memberof ProxyDto
     */
    connectors?: Array<ConnectorSummaryDto>;
}
