// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface ProxyRequestDto
 */
export interface ProxyRequestDto {
    /**
     * Name of the Proxy
     * @type {string}
     * @memberof ProxyRequestDto
     */
    name: string;
    /**
     * Detailed description of the Proxy
     * @type {string}
     * @memberof ProxyRequestDto
     */
    description?: string;
}
