// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { AttributeSetMergeMode, BaseAttributeDto, ValueSourceBindingDto } from './';

/**
 * RA Profile static request-attribute definitions and the merge mode.
 * @export
 * @interface RaProfileCertificateRequestAttributesDto
 */
export interface RaProfileCertificateRequestAttributesDto {
    /**
     * Ordered list of platform-owned request-attribute definitions for this RA Profile
     * @type {Array<BaseAttributeDto>}
     * @memberof RaProfileCertificateRequestAttributesDto
     */
    requestAttributes?: Array<BaseAttributeDto>;
    /**
     * How the static set combines with a connector-supplied set; always the effective mode
     * @type {AttributeSetMergeMode}
     * @memberof RaProfileCertificateRequestAttributesDto
     */
    mergeMode: AttributeSetMergeMode;
    /**
     * Core-side value-source bindings attached onto connector-supplied (or static) definitions by reference
     * @type {Array<ValueSourceBindingDto>}
     * @memberof RaProfileCertificateRequestAttributesDto
     */
    valueSourceBindings?: Array<ValueSourceBindingDto>;
    /**
     * Whether an external CSR violating the resolved set is rejected (true) or accepted with warnings (false); null inherits the platform default
     * @type {boolean}
     * @memberof RaProfileCertificateRequestAttributesDto
     */
    externalCsrValidationStrict?: boolean;
}
