// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { PaginationRequestDto, RequestAttribute } from './';

/**
 * @export
 * @interface RequestAttributeCallback
 */
export interface RequestAttributeCallback {
    /**
     * UUID of the Attribute
     * @type {string}
     * @memberof RequestAttributeCallback
     */
    uuid?: string;
    /**
     * Connector-interface row UUID the form was listed under. Identifies the interface version the callback belongs to for parent-less (Attributes v2) forms.
     * @type {string}
     * @memberof RequestAttributeCallback
     */
    interfaceUuid?: string;
    /**
     * Name of the Attribute
     * @type {string}
     * @memberof RequestAttributeCallback
     */
    name: string;
    /**
     * Map of path variables supported by the callback method
     * @type {{ [key: string]: any; }}
     * @memberof RequestAttributeCallback
     */
    pathVariable?: { [key: string]: any };
    /**
     * Map of the query parameters supported by the callback method
     * @type {{ [key: string]: any; }}
     * @memberof RequestAttributeCallback
     */
    requestParameter?: { [key: string]: any };
    /**
     * Request body for the callback method
     * @type {{ [key: string]: any; }}
     * @memberof RequestAttributeCallback
     */
    body?: { [key: string]: any };
    /**
     * Filter for the resource callback method
     * @type {{ [key: string]: any; }}
     * @memberof RequestAttributeCallback
     */
    filter?: { [key: string]: any };
    /**
     * Pagination of the callback response
     * @type {PaginationRequestDto}
     * @memberof RequestAttributeCallback
     */
    pagination?: PaginationRequestDto;
    /**
     * Attributes v2 callback values: the dependsOn-named attributes the callback consumes, reference-typed values expanded inline by Core. Used by the NG (Attributes v2) callback path.
     * @type {Array<RequestAttribute>}
     * @memberof RequestAttributeCallback
     */
    attributes?: Array<RequestAttribute>;
}
