// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { SimplifiedRaProfileDto } from './';

/**
 * @export
 * @interface ScepProfileDto
 */
export interface ScepProfileDto {
    /**
     * Object identifier
     * @type {string}
     * @memberof ScepProfileDto
     */
    uuid: string;
    /**
     * Object Name
     * @type {string}
     * @memberof ScepProfileDto
     */
    name: string;
    /**
     * Enabled flag - true = enabled; false = disabled
     * @type {boolean}
     * @memberof ScepProfileDto
     */
    enabled: boolean;
    /**
     * SCEP Profile description
     * @type {string}
     * @memberof ScepProfileDto
     */
    description?: string;
    /**
     * RA Profile
     * @type {SimplifiedRaProfileDto}
     * @memberof ScepProfileDto
     */
    raProfile?: SimplifiedRaProfileDto;
    /**
     * Include CA certificate in the SCEP response
     * @type {boolean}
     * @memberof ScepProfileDto
     */
    includeCaCertificate: boolean;
    /**
     * Include CA certificate chain in the SCEP response
     * @type {boolean}
     * @memberof ScepProfileDto
     */
    includeCaCertificateChain: boolean;
    /**
     * Renewal time threshold in days
     * @type {number}
     * @memberof ScepProfileDto
     */
    renewThreshold?: number;
    /**
     * SCEP URL
     * @type {string}
     * @memberof ScepProfileDto
     */
    scepUrl?: string;
    /**
     * Status of Intune
     * @type {boolean}
     * @memberof ScepProfileDto
     */
    enableIntune?: boolean;
    /**
     * Whether a challenge password is currently set for the SCEP Profile. The password value itself is write-only and never returned; this flag lets clients reflect the current state.
     * @type {boolean}
     * @memberof ScepProfileDto
     */
    enableChallengePassword: boolean;
}
