// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { NameAndUuidDto, SigningProfileListDto } from './';

/**
 * Signing Record detail
 * @export
 * @interface SigningRecordDto
 */
export interface SigningRecordDto {
    /**
     * Object identifier
     * @type {string}
     * @memberof SigningRecordDto
     */
    uuid: string;
    /**
     * Object Name
     * @type {string}
     * @memberof SigningRecordDto
     */
    name: string;
    /**
     * Signing Profile used to produce this Signing Record
     * @type {SigningProfileListDto}
     * @memberof SigningRecordDto
     */
    signingProfile: SigningProfileListDto;
    /**
     * Claimed signing time embedded in the signature structure by the signing operation.
     * @type {string}
     * @memberof SigningRecordDto
     */
    signingTime: string;
    /**
     * Identity of the user that requested the signing operation
     * @type {NameAndUuidDto}
     * @memberof SigningRecordDto
     */
    requestedBy?: NameAndUuidDto;
    /**
     * Server time at which the Signing Record was created in the system. This timestamp is set by the platform and is independent of the cryptographic signing time.
     * @type {string}
     * @memberof SigningRecordDto
     */
    createdAt: string;
    /**
     * Raw signature value bytes (Base64-encoded),if recorded.
     * @type {string}
     * @memberof SigningRecordDto
     */
    signatureValue?: string;
    /**
     * Signed document bytes (Base64-encoded), if recorded
     * @type {string}
     * @memberof SigningRecordDto
     */
    signedDocument?: string;
    /**
     * Data-to-be-signed bytes (Base64-encoded), if recorded
     * @type {string}
     * @memberof SigningRecordDto
     */
    dtbs?: string;
    /**
     * Captured request metadata (JSON), if recorded
     * @type {string}
     * @memberof SigningRecordDto
     */
    requestMetadataJson?: string;
    /**
     * Time the signed document was first served via CSC retrieval, if any
     * @type {string}
     * @memberof SigningRecordDto
     */
    signedDocumentRetrievedAt?: string;
}
