// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { SigningRecordPersistenceMode } from './';

/**
 * Effective Signing Record policy on a Signing Profile
 * @export
 * @interface SigningRecordPolicyDto
 */
export interface SigningRecordPolicyDto {
    /**
     * Master switch: when false, no Signing Record is created at all for this profile, regardless of the content policy below
     * @type {boolean}
     * @memberof SigningRecordPolicyDto
     */
    recordingEnabled?: boolean;
    /**
     * Content policy: capture inbound request parameters (algorithm, policy IDs, claimed signer)
     * @type {boolean}
     * @memberof SigningRecordPolicyDto
     */
    recordRequestMetadata?: boolean;
    /**
     * Content policy: capture raw signature value
     * @type {boolean}
     * @memberof SigningRecordPolicyDto
     */
    recordSignature?: boolean;
    /**
     * Content policy: capture assembled signed document (only valid for CONTENT_SIGNING and TIMESTAMPING workflows)
     * @type {boolean}
     * @memberof SigningRecordPolicyDto
     */
    recordSignedDocument?: boolean;
    /**
     * Content policy: capture data-to-be-signed bytes
     * @type {boolean}
     * @memberof SigningRecordPolicyDto
     */
    recordDtbs?: boolean;
    /**
     * Retention in days. null = retain indefinitely.
     * @type {number}
     * @memberof SigningRecordPolicyDto
     */
    retentionDays?: number;
    /**
     * Delete the signed document after CSC API async retrieval succeeds
     * @type {boolean}
     * @memberof SigningRecordPolicyDto
     */
    deleteAfterRetrieval?: boolean;
    /**
     * Persistence-mode trade-off between latency and durability
     * @type {SigningRecordPersistenceMode}
     * @memberof SigningRecordPolicyDto
     */
    persistenceMode?: SigningRecordPersistenceMode;
}
