// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Persistence mode for Signing Records, ordered by descending durability
 * @export
 * @enum {string}
 */
export enum SigningRecordPersistenceMode {
    Immediate = 'immediate',
    DeferredDurable = 'deferred_durable',
    BestEffort = 'best_effort',
}
