// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { SigningProfileListDto, SigningProtocol } from './';

/**
 * Signing Record details for listing
 * @export
 * @interface SigningRecordListDto
 */
export interface SigningRecordListDto {
    /**
     * Object identifier
     * @type {string}
     * @memberof SigningRecordListDto
     */
    uuid: string;
    /**
     * Object Name
     * @type {string}
     * @memberof SigningRecordListDto
     */
    name: string;
    /**
     * Signing Profile used to produce this Signing Record
     * @type {SigningProfileListDto}
     * @memberof SigningRecordListDto
     */
    signingProfile: SigningProfileListDto;
    /**
     * Signing protocol used to produce this Signing Record
     * @type {SigningProtocol}
     * @memberof SigningRecordListDto
     */
    protocol: SigningProtocol;
    /**
     * Claimed signing time embedded in the signature structure by the signing operation.
     * @type {string}
     * @memberof SigningRecordListDto
     */
    signingTime: string;
    /**
     * Server time at which the Signing Record was created in the system. This timestamp is set by the platform and is independent of the cryptographic signing time.
     * @type {string}
     * @memberof SigningRecordListDto
     */
    createdAt: string;
}
