// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { SigningProtocol, SigningScheme, SigningWorkflowType } from './';

/**
 * Signing Profile details for listing
 * @export
 * @interface SigningProfileListDto
 */
export interface SigningProfileListDto {
    /**
     * Object identifier
     * @type {string}
     * @memberof SigningProfileListDto
     */
    uuid: string;
    /**
     * Object Name
     * @type {string}
     * @memberof SigningProfileListDto
     */
    name: string;
    /**
     * Version of the Signing Profile
     * @type {number}
     * @memberof SigningProfileListDto
     */
    version: number;
    /**
     * Description of the Signing Profile
     * @type {string}
     * @memberof SigningProfileListDto
     */
    description?: string;
    /**
     * Signing scheme (managed or delegated)
     * @type {SigningScheme}
     * @memberof SigningProfileListDto
     */
    signingScheme: SigningScheme;
    /**
     * Signing workflow type
     * @type {SigningWorkflowType}
     * @memberof SigningProfileListDto
     */
    signingWorkflowType: SigningWorkflowType;
    /**
     * Whether the Signing Profile is enabled
     * @type {boolean}
     * @memberof SigningProfileListDto
     */
    enabled: boolean;
    /**
     * List of enabled protocols on this Signing Profile.
     * @type {Array<SigningProtocol>}
     * @memberof SigningProfileListDto
     */
    enabledProtocols: Array<SigningProtocol>;
}
