// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @enum {string}
 */
export enum SigningRecordStatisticsPeriod {
    _24h = '24h',
    _7d = '7d',
    _30d = '30d',
    _90d = '90d',
}
