// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Dependency filter that scopes a value source by another attribute\'s value
 * @export
 * @interface SourceParam
 */
export interface SourceParam {
    /**
     * UUID of the attribute whose value is used as a filter parameter
     * @type {string}
     * @memberof SourceParam
     */
    attributeUuid?: string;
    /**
     * Name of the attribute; used as fallback when attributeUuid is not matched
     * @type {string}
     * @memberof SourceParam
     */
    attributeName?: string;
}
