// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Time attribute content in predefined format
 * @export
 * @interface TimeAttributeContentV2
 */
export interface TimeAttributeContentV2 {
    /**
     * ContentV2 Reference
     * @type {string}
     * @memberof TimeAttributeContentV2
     */
    reference?: string;
    /**
     * Time attribute value in format HH:mm:ss
     * @type {string}
     * @memberof TimeAttributeContentV2
     */
    data: string;
}
