// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * TSP activation detail
 * @export
 * @interface TspActivationDetailDto
 */
export interface TspActivationDetailDto {
    /**
     * Object identifier
     * @type {string}
     * @memberof TspActivationDetailDto
     */
    uuid: string;
    /**
     * Object Name
     * @type {string}
     * @memberof TspActivationDetailDto
     */
    name: string;
    /**
     * TSP availability flag - true = activated; false = not activated
     * @type {boolean}
     * @memberof TspActivationDetailDto
     */
    available: boolean;
    /**
     * TSP URL for signing
     * @type {string}
     * @memberof TspActivationDetailDto
     */
    signingUrl?: string;
}
