// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * A Basic (username/password) credential to update on a TSP Profile. The password is write-only: leave it blank to keep the existing secret, or provide a value to rotate it. Changing the username requires a new password.
 * @export
 * @interface TspBasicCredentialUpdateRequestDto
 */
export interface TspBasicCredentialUpdateRequestDto {
    /**
     * Basic username; unique within the TSP profile. Changing it requires a new password.
     * @type {string}
     * @memberof TspBasicCredentialUpdateRequestDto
     */
    username: string;
    /**
     * Basic password (write-only). Blank keeps the existing secret and a value rotates it; a value is also required when the username changes.
     * @type {string}
     * @memberof TspBasicCredentialUpdateRequestDto
     */
    password?: string;
    /**
     * UUID of the real ILM user this credential authenticates as.
     * @type {string}
     * @memberof TspBasicCredentialUpdateRequestDto
     */
    mappedUserUuid: string;
}
