// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { NameAndUuidDto } from './';

/**
 * Read-only view of a Basic credential on a TSP Profile.
 * @export
 * @interface TspBasicCredentialDto
 */
export interface TspBasicCredentialDto {
    /**
     * UUID of this credential
     * @type {string}
     * @memberof TspBasicCredentialDto
     */
    uuid: string;
    /**
     * Basic username
     * @type {string}
     * @memberof TspBasicCredentialDto
     */
    username: string;
    /**
     * The real ILM user this credential authenticates as
     * @type {NameAndUuidDto}
     * @memberof TspBasicCredentialDto
     */
    mappedUser: NameAndUuidDto;
}
