// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * A Basic (username/password) credential to create on a TSP Profile.
 * @export
 * @interface TspBasicCredentialCreateRequestDto
 */
export interface TspBasicCredentialCreateRequestDto {
    /**
     * Basic username; unique within the TSP profile.
     * @type {string}
     * @memberof TspBasicCredentialCreateRequestDto
     */
    username: string;
    /**
     * Basic password (write-only). Required on create.
     * @type {string}
     * @memberof TspBasicCredentialCreateRequestDto
     */
    password: string;
    /**
     * UUID of the real ILM user this credential authenticates as.
     * @type {string}
     * @memberof TspBasicCredentialCreateRequestDto
     */
    mappedUserUuid: string;
}
