// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * A single Basic (username/password) credential on a TSP Profile. The password is write-only: provide it to create or rotate the credential; leave it blank on update to keep the existing secret.
 * @export
 * @interface TspBasicCredentialRequestDto
 */
export interface TspBasicCredentialRequestDto {
    /**
     * Basic username; unique within the TSP profile.
     * @type {string}
     * @memberof TspBasicCredentialRequestDto
     */
    username: string;
    /**
     * Basic password (write-only). On create a value is required — there is no existing secret to keep. On update, blank keeps the existing secret and a value rotates it.
     * @type {string}
     * @memberof TspBasicCredentialRequestDto
     */
    password?: string;
    /**
     * UUID of the real ILM user this credential authenticates as.
     * @type {string}
     * @memberof TspBasicCredentialRequestDto
     */
    mappedUserUuid: string;
}
