// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { SimplifiedSigningProfileDto } from './';

/**
 * TSP (Timestamping Protocol) profile details for listing
 * @export
 * @interface TspProfileListDto
 */
export interface TspProfileListDto {
    /**
     * Object identifier
     * @type {string}
     * @memberof TspProfileListDto
     */
    uuid: string;
    /**
     * Object Name
     * @type {string}
     * @memberof TspProfileListDto
     */
    name: string;
    /**
     * Description of the TSP Profile
     * @type {string}
     * @memberof TspProfileListDto
     */
    description?: string;
    /**
     * Default Signing Profile
     * @type {SimplifiedSigningProfileDto}
     * @memberof TspProfileListDto
     */
    defaultSigningProfile?: SimplifiedSigningProfileDto;
    /**
     * TSP URL for signing
     * @type {string}
     * @memberof TspProfileListDto
     */
    signingUrl?: string;
    /**
     * Enabled flag of the TSP Profile
     * @type {boolean}
     * @memberof TspProfileListDto
     */
    enabled: boolean;
}
