// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { RequestAttribute, TspAuthenticationMethod } from './';

/**
 * Request to create or update a TSP (Timestamping Protocol) Profile
 * @export
 * @interface TspProfileRequestDto
 */
export interface TspProfileRequestDto {
    /**
     * Name of the TSP Profile
     * @type {string}
     * @memberof TspProfileRequestDto
     */
    name: string;
    /**
     * Description of the TSP Profile
     * @type {string}
     * @memberof TspProfileRequestDto
     */
    description?: string;
    /**
     * UUID of the default Signing Profile
     * @type {string}
     * @memberof TspProfileRequestDto
     */
    defaultSigningProfileUuid?: string;
    /**
     * Vault profile that stores this profile\'s Basic credentials; required when Basic credentials are configured
     * @type {string}
     * @memberof TspProfileRequestDto
     */
    vaultProfileUuid?: string;
    /**
     * Authentication methods this TSP Profile accepts on the TSP protocol endpoints. Allowed to be empty for the transitional period.
     * @type {Array<TspAuthenticationMethod>}
     * @memberof TspProfileRequestDto
     */
    allowedAuthenticationMethods?: Array<TspAuthenticationMethod>;
    /**
     * List of Custom Attributes
     * @type {Array<RequestAttribute>}
     * @memberof TspProfileRequestDto
     */
    customAttributes?: Array<RequestAttribute>;
}
