// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ConditionItemRequestDto } from './';

/**
 * @export
 * @interface UpdateConditionRequestDto
 */
export interface UpdateConditionRequestDto {
    /**
     * Name of the condition
     * @type {string}
     * @memberof UpdateConditionRequestDto
     */
    name?: string;
    /**
     * Description of the condition
     * @type {string}
     * @memberof UpdateConditionRequestDto
     */
    description?: string;
    /**
     * List of the condition items to add to condition
     * @type {Array<ConditionItemRequestDto>}
     * @memberof UpdateConditionRequestDto
     */
    items: Array<ConditionItemRequestDto>;
}
