// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ExecutionItemRequestDto } from './';

/**
 * @export
 * @interface UpdateExecutionRequestDto
 */
export interface UpdateExecutionRequestDto {
    /**
     * Name of the execution
     * @type {string}
     * @memberof UpdateExecutionRequestDto
     */
    name?: string;
    /**
     * Description of the execution
     * @type {string}
     * @memberof UpdateExecutionRequestDto
     */
    description?: string;
    /**
     * List of the execution items to add to execution
     * @type {Array<ExecutionItemRequestDto>}
     * @memberof UpdateExecutionRequestDto
     */
    items: Array<ExecutionItemRequestDto>;
}
