// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface UpdateRuleRequestDto
 */
export interface UpdateRuleRequestDto {
    /**
     * Name of the Rule
     * @type {string}
     * @memberof UpdateRuleRequestDto
     */
    name?: string;
    /**
     * Description of the Rule
     * @type {string}
     * @memberof UpdateRuleRequestDto
     */
    description?: string;
    /**
     * List of UUIDs of existing conditions to add to the rule
     * @type {Array<string>}
     * @memberof UpdateRuleRequestDto
     */
    conditionsUuids: Array<string>;
}
