// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { RequestAttribute } from './';

/**
 * @export
 * @interface UpdateUserRequestDto
 */
export interface UpdateUserRequestDto {
    /**
     * Description of the user
     * @type {string}
     * @memberof UpdateUserRequestDto
     */
    description?: string;
    /**
     * First name of the user
     * @type {string}
     * @memberof UpdateUserRequestDto
     */
    firstName?: string;
    /**
     * Last name of the user
     * @type {string}
     * @memberof UpdateUserRequestDto
     */
    lastName?: string;
    /**
     * Email of the user
     * @type {string}
     * @memberof UpdateUserRequestDto
     */
    email?: string;
    /**
     * Groups UUIDs of the user. For creation, omit or provide an empty list for no group membership. For updates, omit to leave the current membership unchanged; set to an empty list to remove the user from all groups.
     * @type {Array<string>}
     * @memberof UpdateUserRequestDto
     */
    groupUuids?: Array<string>;
    /**
     * Base64 content of the user certificate
     * @type {string}
     * @memberof UpdateUserRequestDto
     */
    certificateData?: string;
    /**
     * UUID of the existing certificate in the inventory. Mandatory if certificate data is not provided
     * @type {string}
     * @memberof UpdateUserRequestDto
     */
    certificateUuid?: string;
    /**
     * List of Custom Attributes
     * @type {Array<RequestAttribute>}
     * @memberof UpdateUserRequestDto
     */
    customAttributes?: Array<RequestAttribute>;
    /**
     * List of Custom Attributes set for the user certificate, if a new certificate is uploaded. Ignored if the certificate already exists in the inventory (matched by UUID or fingerprint).
     * @type {Array<RequestAttribute>}
     * @memberof UpdateUserRequestDto
     */
    certificateCustomAttributes?: Array<RequestAttribute>;
}
