// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { SourceParam, ValueSourceType } from './';

/**
 * Declares how Core resolves the content of an attribute; orthogonal to fieldMapping
 * @export
 * @interface ValueSource
 */
export interface ValueSource {
    /**
     * How the attribute value is resolved
     * @type {ValueSourceType}
     * @memberof ValueSource
     */
    kind: ValueSourceType;
    /**
     * Optional dependency filters that scope the source by other attributes\' values
     * @type {Array<SourceParam>}
     * @memberof ValueSource
     */
    params?: Array<SourceParam>;
}
