// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { SourceParam, ValueSourceType } from './';

/**
 * Core-side value-source binding onto a request-attribute definition; binds by attribute UUID (name fallback).
 * @export
 * @interface ValueSourceBindingDto
 */
export interface ValueSourceBindingDto {
    /**
     * UUID of the target attribute definition; primary binding key
     * @type {string}
     * @memberof ValueSourceBindingDto
     */
    attributeUuid?: string;
    /**
     * Name of the target attribute definition; fallback binding key when the UUID is absent or rotated
     * @type {string}
     * @memberof ValueSourceBindingDto
     */
    attributeName?: string;
    /**
     * Value-source provider type to bind onto the target definition
     * @type {ValueSourceType}
     * @memberof ValueSourceBindingDto
     */
    valueSourceType: ValueSourceType;
    /**
     * Reference to a registered collection/source; used by collection-style value sources
     * @type {string}
     * @memberof ValueSourceBindingDto
     */
    collectionRef?: string;
    /**
     * Optional cascading dependency parameters (from other attributes)
     * @type {Array<SourceParam>}
     * @memberof ValueSourceBindingDto
     */
    params?: Array<SourceParam>;
}
