// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Observable } from 'rxjs';
import type { AjaxResponse } from 'rxjs/ajax';
import { BaseAPI, throwIfNullOrUndefined, encodeURI } from '../runtime';
import type { OperationOpts, HttpHeaders } from '../runtime';
import type {
    AuthenticationServiceExceptionDto,
    BaseAttributeDto,
    CancelPendingCertificateRequestDto,
    CertificateDetailDto,
    ClientCertificateDataResponseDto,
    ClientCertificateRekeyRequestDto,
    ClientCertificateRenewRequestDto,
    ClientCertificateRevocationDto,
    ClientCertificateSignRequestDto,
    ErrorMessageDto,
    RequestAttribute,
    UploadCertificateRequestDto,
} from '../models';

export interface CancelPendingCertificateOperationRequest {
    authorityUuid: string;
    raProfileUuid: string;
    certificateUuid: string;
    cancelPendingCertificateRequestDto?: CancelPendingCertificateRequestDto;
}

export interface IssueCertificateRequest {
    authorityUuid: string;
    raProfileUuid: string;
    clientCertificateSignRequestDto: ClientCertificateSignRequestDto;
}

export interface IssueRequestedCertificateRequest {
    authorityUuid: string;
    raProfileUuid: string;
    certificateUuid: string;
}

export interface ListIssueCertificateAttributesRequest {
    authorityUuid: string;
    raProfileUuid: string;
}

export interface ListRevokeCertificateAttributesRequest {
    authorityUuid: string;
    raProfileUuid: string;
}

export interface ManuallyConfirmRevokeRequest {
    authorityUuid: string;
    raProfileUuid: string;
    certificateUuid: string;
}

export interface ManuallyIssueCertificateRequest {
    authorityUuid: string;
    raProfileUuid: string;
    certificateUuid: string;
    uploadCertificateRequestDto: UploadCertificateRequestDto;
}

export interface RekeyCertificateRequest {
    authorityUuid: string;
    raProfileUuid: string;
    certificateUuid: string;
    clientCertificateRekeyRequestDto: ClientCertificateRekeyRequestDto;
}

export interface RenewCertificateRequest {
    authorityUuid: string;
    raProfileUuid: string;
    certificateUuid: string;
    clientCertificateRenewRequestDto: ClientCertificateRenewRequestDto;
}

export interface RevokeCertificateRequest {
    authorityUuid: string;
    raProfileUuid: string;
    certificateUuid: string;
    clientCertificateRevocationDto: ClientCertificateRevocationDto;
}

export interface ValidateIssueCertificateAttributesRequest {
    authorityUuid: string;
    raProfileUuid: string;
    requestAttribute: Array<RequestAttribute>;
}

export interface ValidateRevokeCertificateAttributesRequest {
    authorityUuid: string;
    raProfileUuid: string;
    requestAttribute: Array<RequestAttribute>;
}

/**
 * no description
 */
export class ClientOperationsV2Api extends BaseAPI {
    /**
     * State-aware cancel for a certificate currently in state `PENDING_ISSUE` or `PENDING_REVOKE`. Transitions:  - `PENDING_ISSUE` → `FAILED` - `PENDING_REVOKE` → `ISSUED`  The optional `reason` from the request body is recorded in the certificate event history.  If the underlying operation cannot be aborted (for example, it has progressed beyond a point where cancellation is possible), the response is `422 Unprocessable Entity` with the reason, and the certificate **stays in its pending state**. In that case the operation can still be resolved by waiting for it to complete and then finalizing or confirming the certificate, or by retrying the cancel later if circumstances change.
     * Cancel a pending certificate operation
     */
    cancelPendingCertificateOperation({
        authorityUuid,
        raProfileUuid,
        certificateUuid,
        cancelPendingCertificateRequestDto,
    }: CancelPendingCertificateOperationRequest): Observable<CertificateDetailDto>;
    cancelPendingCertificateOperation(
        { authorityUuid, raProfileUuid, certificateUuid, cancelPendingCertificateRequestDto }: CancelPendingCertificateOperationRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<CertificateDetailDto>>;
    cancelPendingCertificateOperation(
        { authorityUuid, raProfileUuid, certificateUuid, cancelPendingCertificateRequestDto }: CancelPendingCertificateOperationRequest,
        opts?: OperationOpts,
    ): Observable<CertificateDetailDto | AjaxResponse<CertificateDetailDto>> {
        throwIfNullOrUndefined(authorityUuid, 'authorityUuid', 'cancelPendingCertificateOperation');
        throwIfNullOrUndefined(raProfileUuid, 'raProfileUuid', 'cancelPendingCertificateOperation');
        throwIfNullOrUndefined(certificateUuid, 'certificateUuid', 'cancelPendingCertificateOperation');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<CertificateDetailDto>(
            {
                url: '/v2/operations/authorities/{authorityUuid}/raProfiles/{raProfileUuid}/certificates/{certificateUuid}/cancel'
                    .replace('{authorityUuid}', encodeURI(authorityUuid))
                    .replace('{raProfileUuid}', encodeURI(raProfileUuid))
                    .replace('{certificateUuid}', encodeURI(certificateUuid)),
                method: 'POST',
                headers,
                body: cancelPendingCertificateRequestDto,
            },
            opts?.responseOpts,
        );
    }

    /**
     * Submit a new certificate signing request and trigger issuance through this RA profile. If the issuance is asynchronous, the certificate is returned in state `PENDING_ISSUE` and must be finalized once it has been issued.
     * Issue certificate
     */
    issueCertificate({
        authorityUuid,
        raProfileUuid,
        clientCertificateSignRequestDto,
    }: IssueCertificateRequest): Observable<ClientCertificateDataResponseDto>;
    issueCertificate(
        { authorityUuid, raProfileUuid, clientCertificateSignRequestDto }: IssueCertificateRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<ClientCertificateDataResponseDto>>;
    issueCertificate(
        { authorityUuid, raProfileUuid, clientCertificateSignRequestDto }: IssueCertificateRequest,
        opts?: OperationOpts,
    ): Observable<ClientCertificateDataResponseDto | AjaxResponse<ClientCertificateDataResponseDto>> {
        throwIfNullOrUndefined(authorityUuid, 'authorityUuid', 'issueCertificate');
        throwIfNullOrUndefined(raProfileUuid, 'raProfileUuid', 'issueCertificate');
        throwIfNullOrUndefined(clientCertificateSignRequestDto, 'clientCertificateSignRequestDto', 'issueCertificate');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<ClientCertificateDataResponseDto>(
            {
                url: '/v2/operations/authorities/{authorityUuid}/raProfiles/{raProfileUuid}/certificates'
                    .replace('{authorityUuid}', encodeURI(authorityUuid))
                    .replace('{raProfileUuid}', encodeURI(raProfileUuid)),
                method: 'POST',
                headers,
                body: clientCertificateSignRequestDto,
            },
            opts?.responseOpts,
        );
    }

    /**
     * Trigger issuance for a certificate already in state `REQUESTED`. Used after the certificate request has been created (typically via a protocol such as ACME, SCEP, or CMP) and any approval and compliance flows have completed.
     * Issue an existing certificate request
     */
    issueRequestedCertificate({
        authorityUuid,
        raProfileUuid,
        certificateUuid,
    }: IssueRequestedCertificateRequest): Observable<ClientCertificateDataResponseDto>;
    issueRequestedCertificate(
        { authorityUuid, raProfileUuid, certificateUuid }: IssueRequestedCertificateRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<ClientCertificateDataResponseDto>>;
    issueRequestedCertificate(
        { authorityUuid, raProfileUuid, certificateUuid }: IssueRequestedCertificateRequest,
        opts?: OperationOpts,
    ): Observable<ClientCertificateDataResponseDto | AjaxResponse<ClientCertificateDataResponseDto>> {
        throwIfNullOrUndefined(authorityUuid, 'authorityUuid', 'issueRequestedCertificate');
        throwIfNullOrUndefined(raProfileUuid, 'raProfileUuid', 'issueRequestedCertificate');
        throwIfNullOrUndefined(certificateUuid, 'certificateUuid', 'issueRequestedCertificate');

        return this.request<ClientCertificateDataResponseDto>(
            {
                url: '/v2/operations/authorities/{authorityUuid}/raProfiles/{raProfileUuid}/certificates/{certificateUuid}/issue'
                    .replace('{authorityUuid}', encodeURI(authorityUuid))
                    .replace('{raProfileUuid}', encodeURI(raProfileUuid))
                    .replace('{certificateUuid}', encodeURI(certificateUuid)),
                method: 'POST',
            },
            opts?.responseOpts,
        );
    }

    /**
     * Return the list of attributes the client must populate when requesting an issuance through this RA profile. The list reflects the certificate authority\'s current attribute schema.
     * Get issue certificate attributes
     */
    listIssueCertificateAttributes({
        authorityUuid,
        raProfileUuid,
    }: ListIssueCertificateAttributesRequest): Observable<Array<BaseAttributeDto>>;
    listIssueCertificateAttributes(
        { authorityUuid, raProfileUuid }: ListIssueCertificateAttributesRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<Array<BaseAttributeDto>>>;
    listIssueCertificateAttributes(
        { authorityUuid, raProfileUuid }: ListIssueCertificateAttributesRequest,
        opts?: OperationOpts,
    ): Observable<Array<BaseAttributeDto> | AjaxResponse<Array<BaseAttributeDto>>> {
        throwIfNullOrUndefined(authorityUuid, 'authorityUuid', 'listIssueCertificateAttributes');
        throwIfNullOrUndefined(raProfileUuid, 'raProfileUuid', 'listIssueCertificateAttributes');

        return this.request<Array<BaseAttributeDto>>(
            {
                url: '/v2/operations/authorities/{authorityUuid}/raProfiles/{raProfileUuid}/attributes/issue'
                    .replace('{authorityUuid}', encodeURI(authorityUuid))
                    .replace('{raProfileUuid}', encodeURI(raProfileUuid)),
                method: 'GET',
            },
            opts?.responseOpts,
        );
    }

    /**
     * Return the list of attributes the client must populate when revoking a certificate through this RA profile.
     * Get revocation attributes
     */
    listRevokeCertificateAttributes({
        authorityUuid,
        raProfileUuid,
    }: ListRevokeCertificateAttributesRequest): Observable<Array<BaseAttributeDto>>;
    listRevokeCertificateAttributes(
        { authorityUuid, raProfileUuid }: ListRevokeCertificateAttributesRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<Array<BaseAttributeDto>>>;
    listRevokeCertificateAttributes(
        { authorityUuid, raProfileUuid }: ListRevokeCertificateAttributesRequest,
        opts?: OperationOpts,
    ): Observable<Array<BaseAttributeDto> | AjaxResponse<Array<BaseAttributeDto>>> {
        throwIfNullOrUndefined(authorityUuid, 'authorityUuid', 'listRevokeCertificateAttributes');
        throwIfNullOrUndefined(raProfileUuid, 'raProfileUuid', 'listRevokeCertificateAttributes');

        return this.request<Array<BaseAttributeDto>>(
            {
                url: '/v2/operations/authorities/{authorityUuid}/raProfiles/{raProfileUuid}/attributes/revoke'
                    .replace('{authorityUuid}', encodeURI(authorityUuid))
                    .replace('{raProfileUuid}', encodeURI(raProfileUuid)),
                method: 'GET',
            },
            opts?.responseOpts,
        );
    }

    /**
     * Confirm that a revoked certificate has been revoked. The certificate must be in state `PENDING_REVOKE`. The platform applies the destroy-key flag and revoke attributes from the original revoke request, transitions the certificate to `REVOKED`, and clears the data carried over from the original request.
     * Confirm an asynchronous certificate revocation
     */
    manuallyConfirmRevoke({ authorityUuid, raProfileUuid, certificateUuid }: ManuallyConfirmRevokeRequest): Observable<void>;
    manuallyConfirmRevoke(
        { authorityUuid, raProfileUuid, certificateUuid }: ManuallyConfirmRevokeRequest,
        opts?: OperationOpts,
    ): Observable<void | AjaxResponse<void>>;
    manuallyConfirmRevoke(
        { authorityUuid, raProfileUuid, certificateUuid }: ManuallyConfirmRevokeRequest,
        opts?: OperationOpts,
    ): Observable<void | AjaxResponse<void>> {
        throwIfNullOrUndefined(authorityUuid, 'authorityUuid', 'manuallyConfirmRevoke');
        throwIfNullOrUndefined(raProfileUuid, 'raProfileUuid', 'manuallyConfirmRevoke');
        throwIfNullOrUndefined(certificateUuid, 'certificateUuid', 'manuallyConfirmRevoke');

        return this.request<void>(
            {
                url: '/v2/operations/authorities/{authorityUuid}/raProfiles/{raProfileUuid}/certificates/{certificateUuid}/revoke/confirm'
                    .replace('{authorityUuid}', encodeURI(authorityUuid))
                    .replace('{raProfileUuid}', encodeURI(raProfileUuid))
                    .replace('{certificateUuid}', encodeURI(certificateUuid)),
                method: 'POST',
            },
            opts?.responseOpts,
        );
    }

    /**
     * Upload an issued certificate to finalize a certificate currently in state `PENDING_ISSUE`. On success, the certificate transitions to `ISSUED` and is pushed to any pre-associated locations.  Validation: - the certificate request\'s public key must match the uploaded certificate\'s   public key (mandatory); - the certificate request\'s subject DN should match the uploaded certificate\'s   subject DN (warning on mismatch — some CAs canonicalise the DN); - the uploaded certificate must be verifiable against the certificate   authority associated with the RA profile (mandatory).  Request body carries a Base64-encoded single certificate and an optional list of certificate-level custom attributes.
     * Finalize an asynchronous certificate issuance
     */
    manuallyIssueCertificate({
        authorityUuid,
        raProfileUuid,
        certificateUuid,
        uploadCertificateRequestDto,
    }: ManuallyIssueCertificateRequest): Observable<CertificateDetailDto>;
    manuallyIssueCertificate(
        { authorityUuid, raProfileUuid, certificateUuid, uploadCertificateRequestDto }: ManuallyIssueCertificateRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<CertificateDetailDto>>;
    manuallyIssueCertificate(
        { authorityUuid, raProfileUuid, certificateUuid, uploadCertificateRequestDto }: ManuallyIssueCertificateRequest,
        opts?: OperationOpts,
    ): Observable<CertificateDetailDto | AjaxResponse<CertificateDetailDto>> {
        throwIfNullOrUndefined(authorityUuid, 'authorityUuid', 'manuallyIssueCertificate');
        throwIfNullOrUndefined(raProfileUuid, 'raProfileUuid', 'manuallyIssueCertificate');
        throwIfNullOrUndefined(certificateUuid, 'certificateUuid', 'manuallyIssueCertificate');
        throwIfNullOrUndefined(uploadCertificateRequestDto, 'uploadCertificateRequestDto', 'manuallyIssueCertificate');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<CertificateDetailDto>(
            {
                url: '/v2/operations/authorities/{authorityUuid}/raProfiles/{raProfileUuid}/certificates/{certificateUuid}/issue/finalize'
                    .replace('{authorityUuid}', encodeURI(authorityUuid))
                    .replace('{raProfileUuid}', encodeURI(raProfileUuid))
                    .replace('{certificateUuid}', encodeURI(certificateUuid)),
                method: 'POST',
                headers,
                body: uploadCertificateRequestDto,
            },
            opts?.responseOpts,
        );
    }

    /**
     * The rekey operation is used to request a new certificate with a new key pair. The new certificate will be issued with the same subject and attributes as the original certificate, but with a new public key. Therefore, new certificate signing request (CSR) with new key pair needs to be provided, or new key pair managed by the platform needs to be selected. When the same key pair is used, or the subject is changed, the rekey operation will be rejected.
     * Rekey Certificate
     */
    rekeyCertificate({
        authorityUuid,
        raProfileUuid,
        certificateUuid,
        clientCertificateRekeyRequestDto,
    }: RekeyCertificateRequest): Observable<ClientCertificateDataResponseDto>;
    rekeyCertificate(
        { authorityUuid, raProfileUuid, certificateUuid, clientCertificateRekeyRequestDto }: RekeyCertificateRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<ClientCertificateDataResponseDto>>;
    rekeyCertificate(
        { authorityUuid, raProfileUuid, certificateUuid, clientCertificateRekeyRequestDto }: RekeyCertificateRequest,
        opts?: OperationOpts,
    ): Observable<ClientCertificateDataResponseDto | AjaxResponse<ClientCertificateDataResponseDto>> {
        throwIfNullOrUndefined(authorityUuid, 'authorityUuid', 'rekeyCertificate');
        throwIfNullOrUndefined(raProfileUuid, 'raProfileUuid', 'rekeyCertificate');
        throwIfNullOrUndefined(certificateUuid, 'certificateUuid', 'rekeyCertificate');
        throwIfNullOrUndefined(clientCertificateRekeyRequestDto, 'clientCertificateRekeyRequestDto', 'rekeyCertificate');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<ClientCertificateDataResponseDto>(
            {
                url: '/v2/operations/authorities/{authorityUuid}/raProfiles/{raProfileUuid}/certificates/{certificateUuid}/rekey'
                    .replace('{authorityUuid}', encodeURI(authorityUuid))
                    .replace('{raProfileUuid}', encodeURI(raProfileUuid))
                    .replace('{certificateUuid}', encodeURI(certificateUuid)),
                method: 'POST',
                headers,
                body: clientCertificateRekeyRequestDto,
            },
            opts?.responseOpts,
        );
    }

    /**
     * Renew an existing certificate using the same key pair. The original certificate stays in state `ISSUED`; the renewed certificate is returned and, if its issuance is asynchronous, ends in state `PENDING_ISSUE` until it is finalized.
     * Renew certificate
     */
    renewCertificate({
        authorityUuid,
        raProfileUuid,
        certificateUuid,
        clientCertificateRenewRequestDto,
    }: RenewCertificateRequest): Observable<ClientCertificateDataResponseDto>;
    renewCertificate(
        { authorityUuid, raProfileUuid, certificateUuid, clientCertificateRenewRequestDto }: RenewCertificateRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<ClientCertificateDataResponseDto>>;
    renewCertificate(
        { authorityUuid, raProfileUuid, certificateUuid, clientCertificateRenewRequestDto }: RenewCertificateRequest,
        opts?: OperationOpts,
    ): Observable<ClientCertificateDataResponseDto | AjaxResponse<ClientCertificateDataResponseDto>> {
        throwIfNullOrUndefined(authorityUuid, 'authorityUuid', 'renewCertificate');
        throwIfNullOrUndefined(raProfileUuid, 'raProfileUuid', 'renewCertificate');
        throwIfNullOrUndefined(certificateUuid, 'certificateUuid', 'renewCertificate');
        throwIfNullOrUndefined(clientCertificateRenewRequestDto, 'clientCertificateRenewRequestDto', 'renewCertificate');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<ClientCertificateDataResponseDto>(
            {
                url: '/v2/operations/authorities/{authorityUuid}/raProfiles/{raProfileUuid}/certificates/{certificateUuid}/renew'
                    .replace('{authorityUuid}', encodeURI(authorityUuid))
                    .replace('{raProfileUuid}', encodeURI(raProfileUuid))
                    .replace('{certificateUuid}', encodeURI(certificateUuid)),
                method: 'POST',
                headers,
                body: clientCertificateRenewRequestDto,
            },
            opts?.responseOpts,
        );
    }

    /**
     * Revoke a certificate currently in state `ISSUED`. If the revocation is asynchronous, the certificate moves to state `PENDING_REVOKE` and must be confirmed once the revocation has been performed.
     * Revoke certificate
     */
    revokeCertificate({
        authorityUuid,
        raProfileUuid,
        certificateUuid,
        clientCertificateRevocationDto,
    }: RevokeCertificateRequest): Observable<void>;
    revokeCertificate(
        { authorityUuid, raProfileUuid, certificateUuid, clientCertificateRevocationDto }: RevokeCertificateRequest,
        opts?: OperationOpts,
    ): Observable<void | AjaxResponse<void>>;
    revokeCertificate(
        { authorityUuid, raProfileUuid, certificateUuid, clientCertificateRevocationDto }: RevokeCertificateRequest,
        opts?: OperationOpts,
    ): Observable<void | AjaxResponse<void>> {
        throwIfNullOrUndefined(authorityUuid, 'authorityUuid', 'revokeCertificate');
        throwIfNullOrUndefined(raProfileUuid, 'raProfileUuid', 'revokeCertificate');
        throwIfNullOrUndefined(certificateUuid, 'certificateUuid', 'revokeCertificate');
        throwIfNullOrUndefined(clientCertificateRevocationDto, 'clientCertificateRevocationDto', 'revokeCertificate');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<void>(
            {
                url: '/v2/operations/authorities/{authorityUuid}/raProfiles/{raProfileUuid}/certificates/{certificateUuid}/revoke'
                    .replace('{authorityUuid}', encodeURI(authorityUuid))
                    .replace('{raProfileUuid}', encodeURI(raProfileUuid))
                    .replace('{certificateUuid}', encodeURI(certificateUuid)),
                method: 'POST',
                headers,
                body: clientCertificateRevocationDto,
            },
            opts?.responseOpts,
        );
    }

    /**
     * Validate a candidate set of issuance attributes against this RA profile\'s schema before submitting an issuance request. Returns 422 with a list of error messages when the attributes are not acceptable.
     * Validate issue certificate attributes
     */
    validateIssueCertificateAttributes({
        authorityUuid,
        raProfileUuid,
        requestAttribute,
    }: ValidateIssueCertificateAttributesRequest): Observable<void>;
    validateIssueCertificateAttributes(
        { authorityUuid, raProfileUuid, requestAttribute }: ValidateIssueCertificateAttributesRequest,
        opts?: OperationOpts,
    ): Observable<void | AjaxResponse<void>>;
    validateIssueCertificateAttributes(
        { authorityUuid, raProfileUuid, requestAttribute }: ValidateIssueCertificateAttributesRequest,
        opts?: OperationOpts,
    ): Observable<void | AjaxResponse<void>> {
        throwIfNullOrUndefined(authorityUuid, 'authorityUuid', 'validateIssueCertificateAttributes');
        throwIfNullOrUndefined(raProfileUuid, 'raProfileUuid', 'validateIssueCertificateAttributes');
        throwIfNullOrUndefined(requestAttribute, 'requestAttribute', 'validateIssueCertificateAttributes');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<void>(
            {
                url: '/v2/operations/authorities/{authorityUuid}/raProfiles/{raProfileUuid}/attributes/issue/validate'
                    .replace('{authorityUuid}', encodeURI(authorityUuid))
                    .replace('{raProfileUuid}', encodeURI(raProfileUuid)),
                method: 'POST',
                headers,
                body: requestAttribute,
            },
            opts?.responseOpts,
        );
    }

    /**
     * Validate a candidate set of revocation attributes against this RA profile\'s schema before submitting a revocation request.
     * Validate revocation attributes
     */
    validateRevokeCertificateAttributes({
        authorityUuid,
        raProfileUuid,
        requestAttribute,
    }: ValidateRevokeCertificateAttributesRequest): Observable<void>;
    validateRevokeCertificateAttributes(
        { authorityUuid, raProfileUuid, requestAttribute }: ValidateRevokeCertificateAttributesRequest,
        opts?: OperationOpts,
    ): Observable<void | AjaxResponse<void>>;
    validateRevokeCertificateAttributes(
        { authorityUuid, raProfileUuid, requestAttribute }: ValidateRevokeCertificateAttributesRequest,
        opts?: OperationOpts,
    ): Observable<void | AjaxResponse<void>> {
        throwIfNullOrUndefined(authorityUuid, 'authorityUuid', 'validateRevokeCertificateAttributes');
        throwIfNullOrUndefined(raProfileUuid, 'raProfileUuid', 'validateRevokeCertificateAttributes');
        throwIfNullOrUndefined(requestAttribute, 'requestAttribute', 'validateRevokeCertificateAttributes');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<void>(
            {
                url: '/v2/operations/authorities/{authorityUuid}/raProfiles/{raProfileUuid}/attributes/revoke/validate'
                    .replace('{authorityUuid}', encodeURI(authorityUuid))
                    .replace('{raProfileUuid}', encodeURI(raProfileUuid)),
                method: 'POST',
                headers,
                body: requestAttribute,
            },
            opts?.responseOpts,
        );
    }
}
