// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Observable } from 'rxjs';
import type { AjaxResponse } from 'rxjs/ajax';
import { BaseAPI, throwIfNullOrUndefined, encodeURI } from '../runtime';
import type { OperationOpts, HttpHeaders } from '../runtime';
import type {
    AuthenticationServiceExceptionDto,
    BulkActionMessageDto,
    ErrorMessageDto,
    PaginationResponseDtoSigningRecordListDto,
    SearchFieldDataByGroupDto,
    SearchRequestDto,
    SigningRecordDto,
} from '../models';

export interface BulkDeleteSigningRecordsRequest {
    requestBody: Array<string>;
}

export interface DeleteSigningRecordRequest {
    uuid: string;
}

export interface GetSigningRecordRequest {
    uuid: string;
}

export interface ListSigningRecordsRequest {
    searchRequestDto: SearchRequestDto;
}

/**
 * no description
 */
export class SigningRecordManagementApi extends BaseAPI {
    /**
     * Delete multiple Signing Records
     */
    bulkDeleteSigningRecords({ requestBody }: BulkDeleteSigningRecordsRequest): Observable<Array<BulkActionMessageDto>>;
    bulkDeleteSigningRecords(
        { requestBody }: BulkDeleteSigningRecordsRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<Array<BulkActionMessageDto>>>;
    bulkDeleteSigningRecords(
        { requestBody }: BulkDeleteSigningRecordsRequest,
        opts?: OperationOpts,
    ): Observable<Array<BulkActionMessageDto> | AjaxResponse<Array<BulkActionMessageDto>>> {
        throwIfNullOrUndefined(requestBody, 'requestBody', 'bulkDeleteSigningRecords');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<Array<BulkActionMessageDto>>(
            {
                url: '/v1/signingRecords',
                method: 'DELETE',
                headers,
                body: requestBody,
            },
            opts?.responseOpts,
        );
    }

    /**
     * Delete Signing Record
     */
    deleteSigningRecord({ uuid }: DeleteSigningRecordRequest): Observable<void>;
    deleteSigningRecord({ uuid }: DeleteSigningRecordRequest, opts?: OperationOpts): Observable<void | AjaxResponse<void>>;
    deleteSigningRecord({ uuid }: DeleteSigningRecordRequest, opts?: OperationOpts): Observable<void | AjaxResponse<void>> {
        throwIfNullOrUndefined(uuid, 'uuid', 'deleteSigningRecord');

        return this.request<void>(
            {
                url: '/v1/signingRecords/{uuid}'.replace('{uuid}', encodeURI(uuid)),
                method: 'DELETE',
            },
            opts?.responseOpts,
        );
    }

    /**
     * Details of a Signing Record
     */
    getSigningRecord({ uuid }: GetSigningRecordRequest): Observable<SigningRecordDto>;
    getSigningRecord({ uuid }: GetSigningRecordRequest, opts?: OperationOpts): Observable<AjaxResponse<SigningRecordDto>>;
    getSigningRecord(
        { uuid }: GetSigningRecordRequest,
        opts?: OperationOpts,
    ): Observable<SigningRecordDto | AjaxResponse<SigningRecordDto>> {
        throwIfNullOrUndefined(uuid, 'uuid', 'getSigningRecord');

        return this.request<SigningRecordDto>(
            {
                url: '/v1/signingRecords/{uuid}'.replace('{uuid}', encodeURI(uuid)),
                method: 'GET',
            },
            opts?.responseOpts,
        );
    }

    /**
     * List search filters for Signing Records
     */
    listSigningRecordSearchableFields(): Observable<Array<SearchFieldDataByGroupDto>>;
    listSigningRecordSearchableFields(opts?: OperationOpts): Observable<AjaxResponse<Array<SearchFieldDataByGroupDto>>>;
    listSigningRecordSearchableFields(
        opts?: OperationOpts,
    ): Observable<Array<SearchFieldDataByGroupDto> | AjaxResponse<Array<SearchFieldDataByGroupDto>>> {
        return this.request<Array<SearchFieldDataByGroupDto>>(
            {
                url: '/v1/signingRecords/search',
                method: 'GET',
            },
            opts?.responseOpts,
        );
    }

    /**
     * List of Signing Records
     */
    listSigningRecords({ searchRequestDto }: ListSigningRecordsRequest): Observable<PaginationResponseDtoSigningRecordListDto>;
    listSigningRecords(
        { searchRequestDto }: ListSigningRecordsRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<PaginationResponseDtoSigningRecordListDto>>;
    listSigningRecords(
        { searchRequestDto }: ListSigningRecordsRequest,
        opts?: OperationOpts,
    ): Observable<PaginationResponseDtoSigningRecordListDto | AjaxResponse<PaginationResponseDtoSigningRecordListDto>> {
        throwIfNullOrUndefined(searchRequestDto, 'searchRequestDto', 'listSigningRecords');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<PaginationResponseDtoSigningRecordListDto>(
            {
                url: '/v1/signingRecords',
                method: 'POST',
                headers,
                body: searchRequestDto,
            },
            opts?.responseOpts,
        );
    }
}
