// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Observable } from 'rxjs';
import type { AjaxResponse } from 'rxjs/ajax';
import { BaseAPI } from '../runtime';
import type { OperationOpts, HttpQuery } from '../runtime';
import type {
    AuthenticationServiceExceptionDto,
    ErrorMessageDto,
    SigningRecordStatisticsDto,
    SigningRecordStatisticsPeriod,
    StatisticsDto,
} from '../models';

export interface GetSigningRecordStatisticsRequest {
    period?: SigningRecordStatisticsPeriod;
}

export interface GetStatisticsRequest {
    includeArchived?: boolean;
}

/**
 * no description
 */
export class StatisticsDashboardApi extends BaseAPI {
    /**
     * Get Signing Records dashboard statistics
     */
    getSigningRecordStatistics({ period }: GetSigningRecordStatisticsRequest): Observable<SigningRecordStatisticsDto>;
    getSigningRecordStatistics(
        { period }: GetSigningRecordStatisticsRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<SigningRecordStatisticsDto>>;
    getSigningRecordStatistics(
        { period }: GetSigningRecordStatisticsRequest,
        opts?: OperationOpts,
    ): Observable<SigningRecordStatisticsDto | AjaxResponse<SigningRecordStatisticsDto>> {
        const query: HttpQuery = {};

        if (period != null) {
            query['period'] = period;
        }

        return this.request<SigningRecordStatisticsDto>(
            {
                url: '/v1/statistics/signingRecords',
                method: 'GET',
                query,
            },
            opts?.responseOpts,
        );
    }

    /**
     * Get Dashboard/Statistics Details
     */
    getStatistics({ includeArchived }: GetStatisticsRequest): Observable<StatisticsDto>;
    getStatistics({ includeArchived }: GetStatisticsRequest, opts?: OperationOpts): Observable<AjaxResponse<StatisticsDto>>;
    getStatistics(
        { includeArchived }: GetStatisticsRequest,
        opts?: OperationOpts,
    ): Observable<StatisticsDto | AjaxResponse<StatisticsDto>> {
        const query: HttpQuery = {};

        if (includeArchived != null) {
            query['includeArchived'] = includeArchived;
        }

        return this.request<StatisticsDto>(
            {
                url: '/v1/statistics',
                method: 'GET',
                query,
            },
            opts?.responseOpts,
        );
    }
}
