// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Observable } from 'rxjs';
import type { AjaxResponse } from 'rxjs/ajax';
import { BaseAPI, throwIfNullOrUndefined, encodeURI } from '../runtime';
import type { OperationOpts, HttpHeaders } from '../runtime';
import type { AuthenticationServiceExceptionDto, ErrorMessageDto, TspBasicCredentialDto, TspBasicCredentialRequestDto } from '../models';

export interface CreateTspProfileBasicCredentialRequest {
    tspProfileUuid: string;
    tspBasicCredentialRequestDto: TspBasicCredentialRequestDto;
}

export interface DeleteTspProfileBasicCredentialRequest {
    tspProfileUuid: string;
    uuid: string;
}

export interface GetTspProfileBasicCredentialRequest {
    tspProfileUuid: string;
    uuid: string;
}

export interface ListTspProfileBasicCredentialsRequest {
    tspProfileUuid: string;
}

export interface UpdateTspProfileBasicCredentialRequest {
    tspProfileUuid: string;
    uuid: string;
    tspBasicCredentialRequestDto: TspBasicCredentialRequestDto;
}

/**
 * no description
 */
export class TSPProfileBasicCredentialManagementApi extends BaseAPI {
    /**
     * Create a Basic credential
     */
    createTspProfileBasicCredential({
        tspProfileUuid,
        tspBasicCredentialRequestDto,
    }: CreateTspProfileBasicCredentialRequest): Observable<TspBasicCredentialDto>;
    createTspProfileBasicCredential(
        { tspProfileUuid, tspBasicCredentialRequestDto }: CreateTspProfileBasicCredentialRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<TspBasicCredentialDto>>;
    createTspProfileBasicCredential(
        { tspProfileUuid, tspBasicCredentialRequestDto }: CreateTspProfileBasicCredentialRequest,
        opts?: OperationOpts,
    ): Observable<TspBasicCredentialDto | AjaxResponse<TspBasicCredentialDto>> {
        throwIfNullOrUndefined(tspProfileUuid, 'tspProfileUuid', 'createTspProfileBasicCredential');
        throwIfNullOrUndefined(tspBasicCredentialRequestDto, 'tspBasicCredentialRequestDto', 'createTspProfileBasicCredential');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<TspBasicCredentialDto>(
            {
                url: '/v1/tspProfiles/{tspProfileUuid}/basicCredentials'.replace('{tspProfileUuid}', encodeURI(tspProfileUuid)),
                method: 'POST',
                headers,
                body: tspBasicCredentialRequestDto,
            },
            opts?.responseOpts,
        );
    }

    /**
     * Delete a Basic credential
     */
    deleteTspProfileBasicCredential({ tspProfileUuid, uuid }: DeleteTspProfileBasicCredentialRequest): Observable<void>;
    deleteTspProfileBasicCredential(
        { tspProfileUuid, uuid }: DeleteTspProfileBasicCredentialRequest,
        opts?: OperationOpts,
    ): Observable<void | AjaxResponse<void>>;
    deleteTspProfileBasicCredential(
        { tspProfileUuid, uuid }: DeleteTspProfileBasicCredentialRequest,
        opts?: OperationOpts,
    ): Observable<void | AjaxResponse<void>> {
        throwIfNullOrUndefined(tspProfileUuid, 'tspProfileUuid', 'deleteTspProfileBasicCredential');
        throwIfNullOrUndefined(uuid, 'uuid', 'deleteTspProfileBasicCredential');

        return this.request<void>(
            {
                url: '/v1/tspProfiles/{tspProfileUuid}/basicCredentials/{uuid}'
                    .replace('{tspProfileUuid}', encodeURI(tspProfileUuid))
                    .replace('{uuid}', encodeURI(uuid)),
                method: 'DELETE',
            },
            opts?.responseOpts,
        );
    }

    /**
     * Get a Basic credential
     */
    getTspProfileBasicCredential({ tspProfileUuid, uuid }: GetTspProfileBasicCredentialRequest): Observable<TspBasicCredentialDto>;
    getTspProfileBasicCredential(
        { tspProfileUuid, uuid }: GetTspProfileBasicCredentialRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<TspBasicCredentialDto>>;
    getTspProfileBasicCredential(
        { tspProfileUuid, uuid }: GetTspProfileBasicCredentialRequest,
        opts?: OperationOpts,
    ): Observable<TspBasicCredentialDto | AjaxResponse<TspBasicCredentialDto>> {
        throwIfNullOrUndefined(tspProfileUuid, 'tspProfileUuid', 'getTspProfileBasicCredential');
        throwIfNullOrUndefined(uuid, 'uuid', 'getTspProfileBasicCredential');

        return this.request<TspBasicCredentialDto>(
            {
                url: '/v1/tspProfiles/{tspProfileUuid}/basicCredentials/{uuid}'
                    .replace('{tspProfileUuid}', encodeURI(tspProfileUuid))
                    .replace('{uuid}', encodeURI(uuid)),
                method: 'GET',
            },
            opts?.responseOpts,
        );
    }

    /**
     * List Basic credentials of a TSP Profile
     */
    listTspProfileBasicCredentials({ tspProfileUuid }: ListTspProfileBasicCredentialsRequest): Observable<Array<TspBasicCredentialDto>>;
    listTspProfileBasicCredentials(
        { tspProfileUuid }: ListTspProfileBasicCredentialsRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<Array<TspBasicCredentialDto>>>;
    listTspProfileBasicCredentials(
        { tspProfileUuid }: ListTspProfileBasicCredentialsRequest,
        opts?: OperationOpts,
    ): Observable<Array<TspBasicCredentialDto> | AjaxResponse<Array<TspBasicCredentialDto>>> {
        throwIfNullOrUndefined(tspProfileUuid, 'tspProfileUuid', 'listTspProfileBasicCredentials');

        return this.request<Array<TspBasicCredentialDto>>(
            {
                url: '/v1/tspProfiles/{tspProfileUuid}/basicCredentials'.replace('{tspProfileUuid}', encodeURI(tspProfileUuid)),
                method: 'GET',
            },
            opts?.responseOpts,
        );
    }

    /**
     * Update a Basic credential
     */
    updateTspProfileBasicCredential({
        tspProfileUuid,
        uuid,
        tspBasicCredentialRequestDto,
    }: UpdateTspProfileBasicCredentialRequest): Observable<TspBasicCredentialDto>;
    updateTspProfileBasicCredential(
        { tspProfileUuid, uuid, tspBasicCredentialRequestDto }: UpdateTspProfileBasicCredentialRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<TspBasicCredentialDto>>;
    updateTspProfileBasicCredential(
        { tspProfileUuid, uuid, tspBasicCredentialRequestDto }: UpdateTspProfileBasicCredentialRequest,
        opts?: OperationOpts,
    ): Observable<TspBasicCredentialDto | AjaxResponse<TspBasicCredentialDto>> {
        throwIfNullOrUndefined(tspProfileUuid, 'tspProfileUuid', 'updateTspProfileBasicCredential');
        throwIfNullOrUndefined(uuid, 'uuid', 'updateTspProfileBasicCredential');
        throwIfNullOrUndefined(tspBasicCredentialRequestDto, 'tspBasicCredentialRequestDto', 'updateTspProfileBasicCredential');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<TspBasicCredentialDto>(
            {
                url: '/v1/tspProfiles/{tspProfileUuid}/basicCredentials/{uuid}'
                    .replace('{tspProfileUuid}', encodeURI(tspProfileUuid))
                    .replace('{uuid}', encodeURI(uuid)),
                method: 'PUT',
                headers,
                body: tspBasicCredentialRequestDto,
            },
            opts?.responseOpts,
        );
    }
}
