export type {
    UtilsSettingsDto as SettingsUtilsDto,
    UtilsSettingsDto as SettingsUtilsModel,
    CertificateSettingsDto as SettingsCertificatesDto,
    CertificateSettingsDto as SettingsCertificatesModel,
    PlatformSettingsDto as SettingsPlatformDto,
    PlatformSettingsDto as SettingsPlatformModel,
    PlatformSettingsUpdateDto as SettingsPlatformUpdateDto,
    PlatformSettingsUpdateDto as SettingsPlatformUpdateModel,
    LoggingSettingsDto as SettingsLoggingDto,
    LoggingSettingsDto as SettingsLoggingModel,
    ResourceLoggingSettingsDto,
    ResourceLoggingSettingsDto as ResourceLoggingSettingsModel,
    AuditLoggingSettingsDto,
    AuditLoggingSettingsDto as AuditLoggingSettingsModel,
    EventSettingsDto,
    EventSettingsDto as EventSettingsModel,
    EventsSettingsDto,
    EventsSettingsDto as EventsSettingsModel,
} from './openapi';
