// tslint:disable
/**
 * Workflows API
 * REST API for managing workflows resources in the platform
 *
 * The version of the OpenAPI document: 2.17.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Observable } from 'rxjs';
import type { AjaxResponse } from 'rxjs/ajax';
import { BaseAPI, throwIfNullOrUndefined, encodeURI } from '../runtime';
import type { OperationOpts, HttpHeaders, HttpQuery } from '../runtime';
import type {
    AuthenticationServiceExceptionDto,
    ErrorMessageDto,
    EventHistoryRequestDto,
    PaginationResponseDtoEventHistoryDto,
    PaginationResponseDtoObjectEventHistoryDto,
    Resource,
    ResourceEvent,
} from '../models';

export interface GetObjectDefinedEventHistoryRequest {
    event: ResourceEvent;
    resource: Resource;
    uuid: string;
    eventHistoryRequestDto: EventHistoryRequestDto;
}

export interface GetObjectEventHistoryRequest {
    resource: Resource;
    uuid: string;
    itemsPerPage?: number;
    pageNumber?: number;
}

export interface GetPlatformSettingsEventHistoryRequest {
    event: ResourceEvent;
    eventHistoryRequestDto: EventHistoryRequestDto;
}

/**
 * no description
 */
export class WorkflowEventManagementApi extends BaseAPI {
    /**
     * Get history of event defined by an object
     */
    getObjectDefinedEventHistory({
        event,
        resource,
        uuid,
        eventHistoryRequestDto,
    }: GetObjectDefinedEventHistoryRequest): Observable<PaginationResponseDtoEventHistoryDto>;
    getObjectDefinedEventHistory(
        { event, resource, uuid, eventHistoryRequestDto }: GetObjectDefinedEventHistoryRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<PaginationResponseDtoEventHistoryDto>>;
    getObjectDefinedEventHistory(
        { event, resource, uuid, eventHistoryRequestDto }: GetObjectDefinedEventHistoryRequest,
        opts?: OperationOpts,
    ): Observable<PaginationResponseDtoEventHistoryDto | AjaxResponse<PaginationResponseDtoEventHistoryDto>> {
        throwIfNullOrUndefined(event, 'event', 'getObjectDefinedEventHistory');
        throwIfNullOrUndefined(resource, 'resource', 'getObjectDefinedEventHistory');
        throwIfNullOrUndefined(uuid, 'uuid', 'getObjectDefinedEventHistory');
        throwIfNullOrUndefined(eventHistoryRequestDto, 'eventHistoryRequestDto', 'getObjectDefinedEventHistory');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
            ...(this.configuration.apiKey && { 'ssl-client-cert': this.configuration.apiKey('ssl-client-cert') }), // CertificateAuth authentication
        };

        return this.request<PaginationResponseDtoEventHistoryDto>(
            {
                url: '/v1/workflows/events/{event}/{resource}/{uuid}/history'
                    .replace('{event}', encodeURI(event))
                    .replace('{resource}', encodeURI(resource))
                    .replace('{uuid}', encodeURI(uuid)),
                method: 'POST',
                headers,
                body: eventHistoryRequestDto,
            },
            opts?.responseOpts,
        );
    }

    /**
     * Get event history for a resource object
     */
    getObjectEventHistory({
        resource,
        uuid,
        itemsPerPage,
        pageNumber,
    }: GetObjectEventHistoryRequest): Observable<PaginationResponseDtoObjectEventHistoryDto>;
    getObjectEventHistory(
        { resource, uuid, itemsPerPage, pageNumber }: GetObjectEventHistoryRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<PaginationResponseDtoObjectEventHistoryDto>>;
    getObjectEventHistory(
        { resource, uuid, itemsPerPage, pageNumber }: GetObjectEventHistoryRequest,
        opts?: OperationOpts,
    ): Observable<PaginationResponseDtoObjectEventHistoryDto | AjaxResponse<PaginationResponseDtoObjectEventHistoryDto>> {
        throwIfNullOrUndefined(resource, 'resource', 'getObjectEventHistory');
        throwIfNullOrUndefined(uuid, 'uuid', 'getObjectEventHistory');

        const headers: HttpHeaders = {
            ...(this.configuration.apiKey && { 'ssl-client-cert': this.configuration.apiKey('ssl-client-cert') }), // CertificateAuth authentication
        };

        const query: HttpQuery = {};

        if (itemsPerPage != null) {
            query['itemsPerPage'] = itemsPerPage;
        }
        if (pageNumber != null) {
            query['pageNumber'] = pageNumber;
        }

        return this.request<PaginationResponseDtoObjectEventHistoryDto>(
            {
                url: '/v1/workflows/events/{resource}/{uuid}/history'
                    .replace('{resource}', encodeURI(resource))
                    .replace('{uuid}', encodeURI(uuid)),
                method: 'GET',
                headers,
                query,
            },
            opts?.responseOpts,
        );
    }

    /**
     * Get history of event defined in platform settings
     */
    getPlatformSettingsEventHistory({
        event,
        eventHistoryRequestDto,
    }: GetPlatformSettingsEventHistoryRequest): Observable<PaginationResponseDtoEventHistoryDto>;
    getPlatformSettingsEventHistory(
        { event, eventHistoryRequestDto }: GetPlatformSettingsEventHistoryRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<PaginationResponseDtoEventHistoryDto>>;
    getPlatformSettingsEventHistory(
        { event, eventHistoryRequestDto }: GetPlatformSettingsEventHistoryRequest,
        opts?: OperationOpts,
    ): Observable<PaginationResponseDtoEventHistoryDto | AjaxResponse<PaginationResponseDtoEventHistoryDto>> {
        throwIfNullOrUndefined(event, 'event', 'getPlatformSettingsEventHistory');
        throwIfNullOrUndefined(eventHistoryRequestDto, 'eventHistoryRequestDto', 'getPlatformSettingsEventHistory');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
            ...(this.configuration.apiKey && { 'ssl-client-cert': this.configuration.apiKey('ssl-client-cert') }), // CertificateAuth authentication
        };

        return this.request<PaginationResponseDtoEventHistoryDto>(
            {
                url: '/v1/workflows/events/{event}/history'.replace('{event}', encodeURI(event)),
                method: 'POST',
                headers,
                body: eventHistoryRequestDto,
            },
            opts?.responseOpts,
        );
    }
}
