// tslint:disable
/**
 * Workflows API
 * REST API for managing workflows resources in the platform
 *
 * The version of the OpenAPI document: 2.17.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Resource } from './';

/**
 * @export
 * @interface ActionDto
 */
export interface ActionDto {
    /**
     * Object identifier
     * @type {string}
     * @memberof ActionDto
     */
    uuid: string;
    /**
     * Object Name
     * @type {string}
     * @memberof ActionDto
     */
    name: string;
    /**
     * Description of the action
     * @type {string}
     * @memberof ActionDto
     */
    description?: string;
    /**
     * Resource associated with the action
     * @type {Resource}
     * @memberof ActionDto
     */
    resource: Resource;
}
