// tslint:disable
/**
 * Workflows API
 * REST API for managing workflows resources in the platform
 *
 * The version of the OpenAPI document: 2.17.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ConditionItemRequestDto, ConditionType, Resource } from './';

/**
 * @export
 * @interface ConditionRequestDto
 */
export interface ConditionRequestDto {
    /**
     * Name of the condition
     * @type {string}
     * @memberof ConditionRequestDto
     */
    name: string;
    /**
     * Description of the condition
     * @type {string}
     * @memberof ConditionRequestDto
     */
    description?: string;
    /**
     * Type of the condition
     * @type {ConditionType}
     * @memberof ConditionRequestDto
     */
    type: ConditionType;
    /**
     * Resource associated with the condition
     * @type {Resource}
     * @memberof ConditionRequestDto
     */
    resource: Resource;
    /**
     * List of the condition items to add to condition
     * @type {Array<ConditionItemRequestDto>}
     * @memberof ConditionRequestDto
     */
    items: Array<ConditionItemRequestDto>;
}
