// tslint:disable
/**
 * Workflows API
 * REST API for managing workflows resources in the platform
 *
 * The version of the OpenAPI document: 2.17.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Resource } from './';

/**
 * @export
 * @interface ResourceObjectDto
 */
export interface ResourceObjectDto {
    /**
     * Resource of object
     * @type {Resource}
     * @memberof ResourceObjectDto
     */
    resource: Resource;
    /**
     * Object UUID
     * @type {string}
     * @memberof ResourceObjectDto
     */
    objectUuid: string;
    /**
     * Object Name
     * @type {string}
     * @memberof ResourceObjectDto
     */
    name: string;
}
