// tslint:disable
/**
 * Workflows API
 * REST API for managing workflows resources in the platform
 *
 * The version of the OpenAPI document: 2.17.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { TriggerHistoryRecordDto } from './';

/**
 * @export
 * @interface TriggerHistoryObjectTriggerSummaryDto
 */
export interface TriggerHistoryObjectTriggerSummaryDto {
    /**
     * UUID of the object that the trigger has been evaluated on.
     * @type {string}
     * @memberof TriggerHistoryObjectTriggerSummaryDto
     */
    triggerUuid: string;
    /**
     * Reference UUID of the object that the trigger has been evaluated on.
     * @type {string}
     * @memberof TriggerHistoryObjectTriggerSummaryDto
     */
    triggerName: string;
    /**
     * Time at which has the trigger been triggered
     * @type {string}
     * @memberof TriggerHistoryObjectTriggerSummaryDto
     */
    triggeredAt: string;
    /**
     * Additional message.
     * @type {string}
     * @memberof TriggerHistoryObjectTriggerSummaryDto
     */
    message?: string;
    /**
     * If trigger was sending notifications, confirmation whether notification has been sent successfully or not.
     * @type {boolean}
     * @memberof TriggerHistoryObjectTriggerSummaryDto
     */
    notificationsSent?: boolean;
    /**
     * List of records for each action that has not been performed and each condition that has not been evaluated.
     * @type {Array<TriggerHistoryRecordDto>}
     * @memberof TriggerHistoryObjectTriggerSummaryDto
     */
    records: Array<TriggerHistoryRecordDto>;
}
