name: Test Docker image

on:
  pull_request:
    branches: [ main*, feat/*, hotfix/* ]
  workflow_dispatch:

concurrency:
  group: pr-${{ github.event.pull_request.number || github.ref }}-docker-test
  cancel-in-progress: true

permissions:
  contents: read
  security-events: write

jobs:
  test:
    uses: OmniTrustILM/.github/.github/workflows/containers-test.yml@aa8e081b38a5e0249301b3988119c4765a9035b9 # main
    with:
      image: ilm/frontend-administrator
      cache-scope: frontend-administrator
      build-args: |
        VERSION=${{ github.ref_name }}
